/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.esmods.keepersofthestonestwo.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import com.esmods.keepersofthestonestwo.procedures.StoneGetRechargeStateProcedure;
import com.esmods.keepersofthestonestwo.item.*;
import com.esmods.keepersofthestonestwo.PowerMod;

public class PowerModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(PowerMod.MODID);
	public static final DeferredItem<Item> FIRE_STONE;
	public static final DeferredItem<Item> AIR_STONE;
	public static final DeferredItem<Item> EARTH_STONE;
	public static final DeferredItem<Item> WATER_STONE;
	public static final DeferredItem<Item> ETHER_STONE;
	public static final DeferredItem<Item> FIRE_ARMOR_HELMET;
	public static final DeferredItem<Item> FIRE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> FIRE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> FIRE_ARMOR_BOOTS;
	public static final DeferredItem<Item> FIRE_SWORD;
	public static final DeferredItem<Item> AIR_ARMOR_HELMET;
	public static final DeferredItem<Item> AIR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AIR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AIR_ARMOR_BOOTS;
	public static final DeferredItem<Item> AIR_RAPIER;
	public static final DeferredItem<Item> EARTH_ARMOR_HELMET;
	public static final DeferredItem<Item> EARTH_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EARTH_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> EARTH_ARMOR_BOOTS;
	public static final DeferredItem<Item> EARTH_HAMMER;
	public static final DeferredItem<Item> WATER_KATANA;
	public static final DeferredItem<Item> WATER_ARMOR_HELMET;
	public static final DeferredItem<Item> WATER_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> WATER_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> WATER_ARMOR_BOOTS;
	public static final DeferredItem<Item> ETHER_GLAIVE;
	public static final DeferredItem<Item> ETHER_ARMOR_HELMET;
	public static final DeferredItem<Item> ETHER_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ETHER_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ETHER_ARMOR_BOOTS;
	public static final DeferredItem<Item> ICE_STONE;
	public static final DeferredItem<Item> ICE_ARMOR_HELMET;
	public static final DeferredItem<Item> ICE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ICE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ICE_ARMOR_BOOTS;
	public static final DeferredItem<Item> LIGHTNING_STONE;
	public static final DeferredItem<Item> LIGHTNING_ARMOR_HELMET;
	public static final DeferredItem<Item> LIGHTNING_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> LIGHTNING_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> LIGHTNING_ARMOR_BOOTS;
	public static final DeferredItem<Item> MAGIC_FIREBALL;
	public static final DeferredItem<Item> SOUND_STONE;
	public static final DeferredItem<Item> SOUND_ARMOR_HELMET;
	public static final DeferredItem<Item> SOUND_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SOUND_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SOUND_ARMOR_BOOTS;
	public static final DeferredItem<Item> CRYSTAL_STONE;
	public static final DeferredItem<Item> CRYSTAL_ARMOR_HELMET;
	public static final DeferredItem<Item> CRYSTAL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTAL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> CRYSTAL_ARMOR_BOOTS;
	public static final DeferredItem<Item> LAVA_STONE;
	public static final DeferredItem<Item> LAVA_ARMOR_HELMET;
	public static final DeferredItem<Item> LAVA_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> LAVA_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> LAVA_ARMOR_BOOTS;
	public static final DeferredItem<Item> RAIN_STONE;
	public static final DeferredItem<Item> TORNADO_STONE;
	public static final DeferredItem<Item> OCEAN_STONE;
	public static final DeferredItem<Item> PLANTS_STONE;
	public static final DeferredItem<Item> ANIMALS_STONE;
	public static final DeferredItem<Item> METAL_STONE;
	public static final DeferredItem<Item> LIGHT_STONE;
	public static final DeferredItem<Item> SHADOW_STONE;
	public static final DeferredItem<Item> VACUUM_STONE;
	public static final DeferredItem<Item> SUN_STONE;
	public static final DeferredItem<Item> MOON_STONE;
	public static final DeferredItem<Item> SPACE_STONE;
	public static final DeferredItem<Item> TIME_STONE;
	public static final DeferredItem<Item> BLOOD_STONE;
	public static final DeferredItem<Item> TECHNOLOGY_STONE;
	public static final DeferredItem<Item> TELEPORTATION_STONE;
	public static final DeferredItem<Item> EXPLOSION_STONE;
	public static final DeferredItem<Item> AMBER_STONE;
	public static final DeferredItem<Item> CREATION_STONE;
	public static final DeferredItem<Item> DESTRUCTION_STONE;
	public static final DeferredItem<Item> MIST_STONE;
	public static final DeferredItem<Item> SAND_STONE;
	public static final DeferredItem<Item> SPEED_STONE;
	public static final DeferredItem<Item> POISON_STONE;
	public static final DeferredItem<Item> MAGNET_STONE;
	public static final DeferredItem<Item> MUSHROOMS_STONE;
	public static final DeferredItem<Item> MERCURY_STONE;
	public static final DeferredItem<Item> MUSIC_STONE;
	public static final DeferredItem<Item> PLAGUE_STONE;
	public static final DeferredItem<Item> BLUE_FLAME_STONE;
	public static final DeferredItem<Item> GRAVITY_STONE;
	public static final DeferredItem<Item> SMOKE_STONE;
	public static final DeferredItem<Item> FORM_STONE;
	public static final DeferredItem<Item> MIND_STONE;
	public static final DeferredItem<Item> GOLDEN_DUST_STONE;
	public static final DeferredItem<Item> DARKNESS_STONE;
	public static final DeferredItem<Item> ENERGY_STONE;
	public static final DeferredItem<Item> SPIRIT_STONE;
	public static final DeferredItem<Item> ICE_SPEAR;
	public static final DeferredItem<Item> RAIN_ARMOR_HELMET;
	public static final DeferredItem<Item> RAIN_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> RAIN_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> RAIN_ARMOR_BOOTS;
	public static final DeferredItem<Item> TORNADO_ARMOR_HELMET;
	public static final DeferredItem<Item> TORNADO_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TORNADO_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TORNADO_ARMOR_BOOTS;
	public static final DeferredItem<Item> OCEAN_ARMOR_HELMET;
	public static final DeferredItem<Item> OCEAN_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> OCEAN_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> OCEAN_ARMOR_BOOTS;
	public static final DeferredItem<Item> PLANTS_ARMOR_HELMET;
	public static final DeferredItem<Item> PLANTS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PLANTS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> PLANTS_ARMOR_BOOTS;
	public static final DeferredItem<Item> ANIMALS_ARMOR_HELMET;
	public static final DeferredItem<Item> ANIMALS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANIMALS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANIMALS_ARMOR_BOOTS;
	public static final DeferredItem<Item> METAL_ARMOR_HELMET;
	public static final DeferredItem<Item> METAL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> METAL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> METAL_ARMOR_BOOTS;
	public static final DeferredItem<Item> LIGHTNING_FALCHION;
	public static final DeferredItem<Item> SOUND_DAGGER;
	public static final DeferredItem<Item> CRYSTAL_KNIFE;
	public static final DeferredItem<Item> RAIN_BOW;
	public static final DeferredItem<Item> LAVA_HAMMER;
	public static final DeferredItem<Item> TORNADO_AXE;
	public static final DeferredItem<Item> OCEANIC_TRIDENT;
	public static final DeferredItem<Item> GREEN_STAFF;
	public static final DeferredItem<Item> ANIMALS_HALBERD;
	public static final DeferredItem<Item> EMPTY_BATTERY;
	public static final DeferredItem<Item> FIRE_BATTERY;
	public static final DeferredItem<Item> AIR_BATTERY;
	public static final DeferredItem<Item> EARTH_BATTERY;
	public static final DeferredItem<Item> WATER_BATTERY;
	public static final DeferredItem<Item> ETHER_BATTERY;
	public static final DeferredItem<Item> ICE_BATTERY;
	public static final DeferredItem<Item> LIGHTNING_BATTERY;
	public static final DeferredItem<Item> RIGHT_METAL_GAUNTLET;
	public static final DeferredItem<Item> LEFT_METAL_GAUNTLET;
	public static final DeferredItem<Item> SOUND_BATTERY;
	public static final DeferredItem<Item> CRYSTAL_BATTERY;
	public static final DeferredItem<Item> LAVA_BATTERY;
	public static final DeferredItem<Item> RAIN_BATTERY;
	public static final DeferredItem<Item> TORNADO_BATTERY;
	public static final DeferredItem<Item> OCEAN_BATTERY;
	public static final DeferredItem<Item> PLANTS_BATTERY;
	public static final DeferredItem<Item> ANIMALS_BATTERY;
	public static final DeferredItem<Item> METAL_BATTERY;
	public static final DeferredItem<Item> LIGHT_ARMOR_HELMET;
	public static final DeferredItem<Item> LIGHT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> LIGHT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> LIGHT_ARMOR_BOOTS;
	public static final DeferredItem<Item> LIGHT_BATTERY;
	public static final DeferredItem<Item> LIGHT_SWORD;
	public static final DeferredItem<Item> SHADOW_ARMOR_HELMET;
	public static final DeferredItem<Item> SHADOW_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SHADOW_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SHADOW_ARMOR_BOOTS;
	public static final DeferredItem<Item> SHADOW_BATTERY;
	public static final DeferredItem<Item> DEPLETED_ENERGIUM_INGOT;
	public static final DeferredItem<Item> DEPLETED_ENERGIUM_ORE;
	public static final DeferredItem<Item> DEPLETED_ENERGIUM_BLOCK;
	public static final DeferredItem<Item> RAW_DEPLETED_ENERGIUM;
	public static final DeferredItem<Item> ENERGIUM_INGOT;
	public static final DeferredItem<Item> ENERGIUM_BLOCK;
	public static final DeferredItem<Item> SHADOW_SCYTHE;
	public static final DeferredItem<Item> VACUUM_ARMOR_HELMET;
	public static final DeferredItem<Item> VACUUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> VACUUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> VACUUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> VACUUM_BATTERY;
	public static final DeferredItem<Item> BATTERY_CHARGER;
	public static final DeferredItem<Item> VACUUM_DAGGER;
	public static final DeferredItem<Item> ENERGIUM_UPGRADE_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> ENERGIUM_PICKAXE;
	public static final DeferredItem<Item> ENERGIUM_AXE;
	public static final DeferredItem<Item> ENERGIUM_SWORD;
	public static final DeferredItem<Item> ENERGIUM_SHOVEL;
	public static final DeferredItem<Item> ENERGIUM_HOE;
	public static final DeferredItem<Item> ENERGIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> ENERGIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ENERGIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ENERGIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> ENERGY_ARMOR_HELMET;
	public static final DeferredItem<Item> ENERGY_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ENERGY_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ENERGY_ARMOR_BOOTS;
	public static final DeferredItem<Item> ENERGY_BATTERY;
	public static final DeferredItem<Item> ENERGIUM_CORE;
	public static final DeferredItem<Item> ENERGY_STAFF;
	public static final DeferredItem<Item> KEEPERS_BOX;
	public static final DeferredItem<Item> SUN_ARMOR_HELMET;
	public static final DeferredItem<Item> SUN_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SUN_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SUN_ARMOR_BOOTS;
	public static final DeferredItem<Item> SUN_BATTERY;
	public static final DeferredItem<Item> SOLAR_BLADE;
	public static final DeferredItem<Item> MOON_ARMOR_HELMET;
	public static final DeferredItem<Item> MOON_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MOON_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MOON_ARMOR_BOOTS;
	public static final DeferredItem<Item> MOON_BATTERY;
	public static final DeferredItem<Item> MOON_DOUBLE_SIDED_SPEAR;
	public static final DeferredItem<Item> MOON_BLOCK;
	public static final DeferredItem<Item> SPACE_ARMOR_HELMET;
	public static final DeferredItem<Item> SPACE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SPACE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SPACE_ARMOR_BOOTS;
	public static final DeferredItem<Item> SPACE_BATTERY;
	public static final DeferredItem<Item> CONSTELLATION_SWORD;
	public static final DeferredItem<Item> TIME_ARMOR_HELMET;
	public static final DeferredItem<Item> TIME_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TIME_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TIME_ARMOR_BOOTS;
	public static final DeferredItem<Item> TIME_BATTERY;
	public static final DeferredItem<Item> TIME_KHOPESH;
	public static final DeferredItem<Item> CREATION_ARMOR_HELMET;
	public static final DeferredItem<Item> CREATION_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> CREATION_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> CREATION_ARMOR_BOOTS;
	public static final DeferredItem<Item> CREATION_BATTERY;
	public static final DeferredItem<Item> ENERGIUM_CONTROLLER;
	public static final DeferredItem<Item> CREATION_STAFF;
	public static final DeferredItem<Item> AMPLIFIER_ORE;
	public static final DeferredItem<Item> AMPLIFIER_DROP;
	public static final DeferredItem<Item> RAW_AMPLIFIER;
	public static final DeferredItem<Item> CREATION_SWORD;
	public static final DeferredItem<Item> CREATION_PICKAXE;
	public static final DeferredItem<Item> CREATION_AXE;
	public static final DeferredItem<Item> CREATION_HOE;
	public static final DeferredItem<Item> CREATION_SHOVEL;
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_HELMET;
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_BOOTS;
	public static final DeferredItem<Item> DESTRUCTION_BATTERY;
	public static final DeferredItem<Item> DESTRUCTION_BROADSWORD;
	public static final DeferredItem<Item> AMPLIFIER_BLOCK;
	public static final DeferredItem<Item> BLOOD_ARMOR_HELMET;
	public static final DeferredItem<Item> BLOOD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BLOOD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BLOOD_ARMOR_BOOTS;
	public static final DeferredItem<Item> BLOOD_SICKLE;
	public static final DeferredItem<Item> BLOOD_BATTERY;
	public static final DeferredItem<Item> RAW_DEPLETED_ENERGIUM_BLOCK;
	public static final DeferredItem<Item> RAW_AMPLIFIER_BLOCK;
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_HELMET;
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_BOOTS;
	public static final DeferredItem<Item> TECHNOLOGY_BATTERY;
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_HELMET;
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_BOOTS;
	public static final DeferredItem<Item> TECHNO_PICKAXE;
	public static final DeferredItem<Item> TELEPORTATION_BATTERY;
	public static final DeferredItem<Item> BLUE_PORTAL;
	public static final DeferredItem<Item> ORANGE_PORTAL;
	public static final DeferredItem<Item> EXPLOSION_ARMOR_HELMET;
	public static final DeferredItem<Item> EXPLOSION_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EXPLOSION_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> EXPLOSION_ARMOR_BOOTS;
	public static final DeferredItem<Item> EXPLOSION_BATTERY;
	public static final DeferredItem<Item> EXPLOSION_MACE;
	public static final DeferredItem<Item> AMBER_ARMOR_HELMET;
	public static final DeferredItem<Item> AMBER_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AMBER_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AMBER_ARMOR_BOOTS;
	public static final DeferredItem<Item> AMBER_BATTERY;
	public static final DeferredItem<Item> AMBER_STAFF;
	public static final DeferredItem<Item> AMBER_BLOCK;
	public static final DeferredItem<Item> AMPLIFIER_RING;
	public static final DeferredItem<Item> CURSED_STONE;
	public static final DeferredItem<Item> CURSED_STONE_BRICKS;
	public static final DeferredItem<Item> CURSED_STONE_STAIRS;
	public static final DeferredItem<Item> CURSED_STONE_SLAB;
	public static final DeferredItem<Item> CURSED_STONE_BRICKS_STAIRS;
	public static final DeferredItem<Item> CURSED_STONE_BRICKS_SLAB;
	public static final DeferredItem<Item> CURSED_STONE_WALL;
	public static final DeferredItem<Item> CURSED_STONE_BRICKS_WALL;
	public static final DeferredItem<Item> POLISHED_CURSED_STONE;
	public static final DeferredItem<Item> POLISHED_CURSED_STONE_STAIRS;
	public static final DeferredItem<Item> POLISHED_CURSED_STONE_SLAB;
	public static final DeferredItem<Item> POLISHED_CURSED_STONE_WALL;
	public static final DeferredItem<Item> CURSED_STONE_PILLAR;
	public static final DeferredItem<Item> CURSED_LANTERN;
	public static final DeferredItem<Item> COPYRIUM_INGOT;
	public static final DeferredItem<Item> COPYRIUM_ORE;
	public static final DeferredItem<Item> COPYRIUM_BLOCK;
	public static final DeferredItem<Item> RAW_COPYRIUM;
	public static final DeferredItem<Item> RAW_COPYRIUM_BLOCK;
	public static final DeferredItem<Item> ELEMENTAL_POWER_GENERATOR;
	public static final DeferredItem<Item> MIST_ARMOR_HELMET;
	public static final DeferredItem<Item> MIST_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MIST_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MIST_ARMOR_BOOTS;
	public static final DeferredItem<Item> MIST_BATTERY;
	public static final DeferredItem<Item> MISTY_FAN;
	public static final DeferredItem<Item> CURSED_VAULT;
	public static final DeferredItem<Item> CURSED_KEY;
	public static final DeferredItem<Item> SAND_ARMOR_HELMET;
	public static final DeferredItem<Item> SAND_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SAND_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SAND_ARMOR_BOOTS;
	public static final DeferredItem<Item> SAND_BATTERY;
	public static final DeferredItem<Item> SAND_SABER;
	public static final DeferredItem<Item> SPEED_ARMOR_HELMET;
	public static final DeferredItem<Item> SPEED_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SPEED_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SPEED_ARMOR_BOOTS;
	public static final DeferredItem<Item> SPEED_BATTERY;
	public static final DeferredItem<Item> HIGHSPEED_DAGGER;
	public static final DeferredItem<Item> POISON_ARMOR_HELMET;
	public static final DeferredItem<Item> POISON_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> POISON_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> POISON_ARMOR_BOOTS;
	public static final DeferredItem<Item> POISON_BATTERY;
	public static final DeferredItem<Item> POISON_BOW;
	public static final DeferredItem<Item> MAGNET_ARMOR_HELMET;
	public static final DeferredItem<Item> MAGNET_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MAGNET_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MAGNET_ARMOR_BOOTS;
	public static final DeferredItem<Item> MAGNET_BATTERY;
	public static final DeferredItem<Item> MAGNET_CLAWS;
	public static final DeferredItem<Item> CURSED_LADDER;
	public static final DeferredItem<Item> CURSED_LAMP;
	public static final DeferredItem<Item> TELEPORTATION_BLADE;
	public static final DeferredItem<Item> ENERGIUM_VAULT;
	public static final DeferredItem<Item> ENERGIUM_KEY;
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_HELMET;
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_BOOTS;
	public static final DeferredItem<Item> MUSHROOMS_BATTERY;
	public static final DeferredItem<Item> MUSHROOMS_HAMMER;
	public static final DeferredItem<Item> PURPLE_MUSHROOM;
	public static final DeferredItem<Item> MERCURY_ARMOR_HELMET;
	public static final DeferredItem<Item> MERCURY_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MERCURY_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MERCURY_ARMOR_BOOTS;
	public static final DeferredItem<Item> LUCK_COIN;
	public static final DeferredItem<Item> RAW_ENERGIUM;
	public static final DeferredItem<Item> ENERGIUM_ORE;
	public static final DeferredItem<Item> ENERGIUM_DUST;
	public static final DeferredItem<Item> RAW_ENERGIUM_BLOCK;
	public static final DeferredItem<Item> MERCURY_BATTERY;
	public static final DeferredItem<Item> MERCURY_BATTLE_AXE;
	public static final DeferredItem<Item> DEEPSLATE_DEPLETED_ENERGIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_ENERGIUM_ORE;
	public static final DeferredItem<Item> DEEPSLATE_AMPLIFIER_ORE;
	public static final DeferredItem<Item> DEEPSLATE_COPYRIUM_ORE;
	public static final DeferredItem<Item> MERCURY_BALL;
	public static final DeferredItem<Item> CHISELED_CURSED_STONE;
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS;
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS_SLAB;
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS_STAIRS;
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS_WALL;
	public static final DeferredItem<Item> MUSIC_ARMOR_HELMET;
	public static final DeferredItem<Item> MUSIC_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MUSIC_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MUSIC_ARMOR_BOOTS;
	public static final DeferredItem<Item> MUSIC_BATTERY;
	public static final DeferredItem<Item> MUSIC_GUITAR;
	public static final DeferredItem<Item> FREAKING_PARSNIP;
	public static final DeferredItem<Item> FREAKING_PARSNIP_BLOCK;
	public static final DeferredItem<Item> FREAKING_PARSNIP_SOUP;
	public static final DeferredItem<Item> PLAGUE_ARMOR_HELMET;
	public static final DeferredItem<Item> PLAGUE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PLAGUE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> PLAGUE_ARMOR_BOOTS;
	public static final DeferredItem<Item> PLAGUE_BATTERY;
	public static final DeferredItem<Item> PLAGUE_WALKING_STICK;
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_HELMET;
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_BOOTS;
	public static final DeferredItem<Item> BLUE_FLAME_BATTERY;
	public static final DeferredItem<Item> BLUE_MAGIC_FIREBALL;
	public static final DeferredItem<Item> BLUE_FLAME_SWORD;
	public static final DeferredItem<Item> GRAVITY_ARMOR_HELMET;
	public static final DeferredItem<Item> GRAVITY_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> GRAVITY_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> GRAVITY_ARMOR_BOOTS;
	public static final DeferredItem<Item> GRAVITY_BATTERY;
	public static final DeferredItem<Item> GRAVITY_MACE;
	public static final DeferredItem<Item> SMOKE_ARMOR_HELMET;
	public static final DeferredItem<Item> SMOKE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SMOKE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SMOKE_ARMOR_BOOTS;
	public static final DeferredItem<Item> SMOKE_BATTERY;
	public static final DeferredItem<Item> SMOKE_MUSKET;
	public static final DeferredItem<Item> SPIRIT_ARMOR_HELMET;
	public static final DeferredItem<Item> SPIRIT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SPIRIT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SPIRIT_ARMOR_BOOTS;
	public static final DeferredItem<Item> SPIRIT_BATTERY;
	public static final DeferredItem<Item> SPIRIT_SICKLE;
	public static final DeferredItem<Item> FORM_ARMOR_HELMET;
	public static final DeferredItem<Item> FORM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> FORM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> FORM_ARMOR_BOOTS;
	public static final DeferredItem<Item> FORM_BATTERY;
	public static final DeferredItem<Item> FORM_SAI;
	public static final DeferredItem<Item> MIND_ARMOR_HELMET;
	public static final DeferredItem<Item> MIND_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MIND_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MIND_ARMOR_BOOTS;
	public static final DeferredItem<Item> MIND_BATTERY;
	public static final DeferredItem<Item> MIND_EPEE;
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_HELMET;
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_BOOTS;
	public static final DeferredItem<Item> GOLDEN_DUST_BATTERY;
	public static final DeferredItem<Item> GOLDEN_DUST_STAFF;
	public static final DeferredItem<Item> DARKNESS_ARMOR_HELMET;
	public static final DeferredItem<Item> DARKNESS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DARKNESS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DARKNESS_ARMOR_BOOTS;
	public static final DeferredItem<Item> DARKNESS_BATTERY;
	public static final DeferredItem<Item> DARK_SWORD;
	public static final DeferredItem<Item> THIRST_ARMOR_HELMET;
	public static final DeferredItem<Item> THIRST_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> THIRST_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> THIRST_ARMOR_BOOTS;
	public static final DeferredItem<Item> CHAOS_ARMOR_HELMET;
	public static final DeferredItem<Item> CHAOS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> CHAOS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> CHAOS_ARMOR_BOOTS;
	public static final DeferredItem<Item> HORROR_ARMOR_HELMET;
	public static final DeferredItem<Item> HORROR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> HORROR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> HORROR_ARMOR_BOOTS;
	public static final DeferredItem<Item> FILTH_ARMOR_HELMET;
	public static final DeferredItem<Item> FILTH_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> FILTH_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> FILTH_ARMOR_BOOTS;
	public static final DeferredItem<Item> EMPTY_CHARACTERISTICS_CARD;
	public static final DeferredItem<Item> CHARACTERISTICS_CARD;
	public static final DeferredItem<Item> MUSIC_DISC_CALL_OF_THE_PAST;
	public static final DeferredItem<Item> MUSIC_DISC_ANCIENT_MOOD;
	public static final DeferredItem<Item> CURSED_KNIGHT_SPAWN_EGG;
	public static final DeferredItem<Item> ENERGIUM_GOLEM_SPAWN_EGG;
	public static final DeferredItem<Item> CURSED_SQUIRE_SPAWN_EGG;
	public static final DeferredItem<Item> CURSED_KEEPER_SPAWN_EGG;
	public static final DeferredItem<Item> KEEPERS_BOOK;
	public static final DeferredItem<Item> RUNE_CUTTER;
	public static final DeferredItem<Item> EXTRA_STAR_POINTS_RUNE_1;
	public static final DeferredItem<Item> EXTRA_STAR_POINTS_RUNE_2;
	public static final DeferredItem<Item> EXTRA_STAR_POINTS_RUNE_3;
	public static final DeferredItem<Item> MUSIC_HOPE;
	public static final DeferredItem<Item> ENERGIUM_SHIELD;
	public static final DeferredItem<Item> REDUCED_STONE_RECHARGE_TIME_RUNE_1;
	public static final DeferredItem<Item> REDUCED_STONE_RECHARGE_TIME_RUNE_2;
	public static final DeferredItem<Item> REDUCED_STONE_RECHARGE_TIME_RUNE_3;
	public static final DeferredItem<Item> ADDITION_TIME_MASTER_EFFECT_RUNE_1;
	public static final DeferredItem<Item> ADDITION_TIME_MASTER_EFFECT_RUNE_2;
	public static final DeferredItem<Item> ADDITION_TIME_MASTER_EFFECT_RUNE_3;
	public static final DeferredItem<Item> HEAT_STONE;
	public static final DeferredItem<Item> HEAT_ARMOR_HELMET;
	public static final DeferredItem<Item> HEAT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> HEAT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> HEAT_ARMOR_BOOTS;
	public static final DeferredItem<Item> HEAT_KNIFE;
	public static final DeferredItem<Item> HEAT_BATTERY;
	public static final DeferredItem<Item> SHOCKWAVE_STONE;
	public static final DeferredItem<Item> SHOCKWAVE_ARMOR_HELMET;
	public static final DeferredItem<Item> SHOCKWAVE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SHOCKWAVE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SHOCKWAVE_ARMOR_BOOTS;
	public static final DeferredItem<Item> SHOCKWAVE_GUN;
	public static final DeferredItem<Item> SHOCKWAVE_BATTERY;
	public static final DeferredItem<Item> PROTECTION_RUNE;
	public static final DeferredItem<Item> SPIN_RUNE;
	public static final DeferredItem<Item> DODGING_RUNE;
	public static final DeferredItem<Item> INVISIBILITY_RUNE;
	public static final DeferredItem<Item> HEALING_RUNE;
	public static final DeferredItem<Item> UNKNOWN_RUNE;
	public static final DeferredItem<Item> CURSED_WORLD;
	public static final DeferredItem<Item> COLORS_STONE;
	public static final DeferredItem<Item> COLORS_ARMOR_HELMET;
	public static final DeferredItem<Item> COLORS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> COLORS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> COLORS_ARMOR_BOOTS;
	public static final DeferredItem<Item> COLORS_BATTERY;
	public static final DeferredItem<Item> SPEAR_BRUSH;
	public static final DeferredItem<Item> CURSED_GRASS_BLOCK;
	public static final DeferredItem<Item> CURSED_DIRT;
	static {
		FIRE_STONE = REGISTRY.register("fire_stone", FireStoneItem::new);
		AIR_STONE = REGISTRY.register("air_stone", AirStoneItem::new);
		EARTH_STONE = REGISTRY.register("earth_stone", EarthStoneItem::new);
		WATER_STONE = REGISTRY.register("water_stone", WaterStoneItem::new);
		ETHER_STONE = REGISTRY.register("ether_stone", EtherStoneItem::new);
		FIRE_ARMOR_HELMET = REGISTRY.register("fire_armor_helmet", FireArmorItem.Helmet::new);
		FIRE_ARMOR_CHESTPLATE = REGISTRY.register("fire_armor_chestplate", FireArmorItem.Chestplate::new);
		FIRE_ARMOR_LEGGINGS = REGISTRY.register("fire_armor_leggings", FireArmorItem.Leggings::new);
		FIRE_ARMOR_BOOTS = REGISTRY.register("fire_armor_boots", FireArmorItem.Boots::new);
		FIRE_SWORD = REGISTRY.register("fire_sword", FireSwordItem::new);
		AIR_ARMOR_HELMET = REGISTRY.register("air_armor_helmet", AirArmorItem.Helmet::new);
		AIR_ARMOR_CHESTPLATE = REGISTRY.register("air_armor_chestplate", AirArmorItem.Chestplate::new);
		AIR_ARMOR_LEGGINGS = REGISTRY.register("air_armor_leggings", AirArmorItem.Leggings::new);
		AIR_ARMOR_BOOTS = REGISTRY.register("air_armor_boots", AirArmorItem.Boots::new);
		AIR_RAPIER = REGISTRY.register("air_rapier", AirRapierItem::new);
		EARTH_ARMOR_HELMET = REGISTRY.register("earth_armor_helmet", EarthArmorItem.Helmet::new);
		EARTH_ARMOR_CHESTPLATE = REGISTRY.register("earth_armor_chestplate", EarthArmorItem.Chestplate::new);
		EARTH_ARMOR_LEGGINGS = REGISTRY.register("earth_armor_leggings", EarthArmorItem.Leggings::new);
		EARTH_ARMOR_BOOTS = REGISTRY.register("earth_armor_boots", EarthArmorItem.Boots::new);
		EARTH_HAMMER = REGISTRY.register("earth_hammer", EarthHammerItem::new);
		WATER_KATANA = REGISTRY.register("water_katana", WaterKatanaItem::new);
		WATER_ARMOR_HELMET = REGISTRY.register("water_armor_helmet", WaterArmorItem.Helmet::new);
		WATER_ARMOR_CHESTPLATE = REGISTRY.register("water_armor_chestplate", WaterArmorItem.Chestplate::new);
		WATER_ARMOR_LEGGINGS = REGISTRY.register("water_armor_leggings", WaterArmorItem.Leggings::new);
		WATER_ARMOR_BOOTS = REGISTRY.register("water_armor_boots", WaterArmorItem.Boots::new);
		ETHER_GLAIVE = REGISTRY.register("ether_glaive", EtherGlaiveItem::new);
		ETHER_ARMOR_HELMET = REGISTRY.register("ether_armor_helmet", EtherArmorItem.Helmet::new);
		ETHER_ARMOR_CHESTPLATE = REGISTRY.register("ether_armor_chestplate", EtherArmorItem.Chestplate::new);
		ETHER_ARMOR_LEGGINGS = REGISTRY.register("ether_armor_leggings", EtherArmorItem.Leggings::new);
		ETHER_ARMOR_BOOTS = REGISTRY.register("ether_armor_boots", EtherArmorItem.Boots::new);
		ICE_STONE = REGISTRY.register("ice_stone", IceStoneItem::new);
		ICE_ARMOR_HELMET = REGISTRY.register("ice_armor_helmet", IceArmorItem.Helmet::new);
		ICE_ARMOR_CHESTPLATE = REGISTRY.register("ice_armor_chestplate", IceArmorItem.Chestplate::new);
		ICE_ARMOR_LEGGINGS = REGISTRY.register("ice_armor_leggings", IceArmorItem.Leggings::new);
		ICE_ARMOR_BOOTS = REGISTRY.register("ice_armor_boots", IceArmorItem.Boots::new);
		LIGHTNING_STONE = REGISTRY.register("lightning_stone", LightningStoneItem::new);
		LIGHTNING_ARMOR_HELMET = REGISTRY.register("lightning_armor_helmet", LightningArmorItem.Helmet::new);
		LIGHTNING_ARMOR_CHESTPLATE = REGISTRY.register("lightning_armor_chestplate", LightningArmorItem.Chestplate::new);
		LIGHTNING_ARMOR_LEGGINGS = REGISTRY.register("lightning_armor_leggings", LightningArmorItem.Leggings::new);
		LIGHTNING_ARMOR_BOOTS = REGISTRY.register("lightning_armor_boots", LightningArmorItem.Boots::new);
		MAGIC_FIREBALL = REGISTRY.register("magic_fireball", MagicFireballItem::new);
		SOUND_STONE = REGISTRY.register("sound_stone", SoundStoneItem::new);
		SOUND_ARMOR_HELMET = REGISTRY.register("sound_armor_helmet", SoundArmorItem.Helmet::new);
		SOUND_ARMOR_CHESTPLATE = REGISTRY.register("sound_armor_chestplate", SoundArmorItem.Chestplate::new);
		SOUND_ARMOR_LEGGINGS = REGISTRY.register("sound_armor_leggings", SoundArmorItem.Leggings::new);
		SOUND_ARMOR_BOOTS = REGISTRY.register("sound_armor_boots", SoundArmorItem.Boots::new);
		CRYSTAL_STONE = REGISTRY.register("crystal_stone", CrystalStoneItem::new);
		CRYSTAL_ARMOR_HELMET = REGISTRY.register("crystal_armor_helmet", CrystalArmorItem.Helmet::new);
		CRYSTAL_ARMOR_CHESTPLATE = REGISTRY.register("crystal_armor_chestplate", CrystalArmorItem.Chestplate::new);
		CRYSTAL_ARMOR_LEGGINGS = REGISTRY.register("crystal_armor_leggings", CrystalArmorItem.Leggings::new);
		CRYSTAL_ARMOR_BOOTS = REGISTRY.register("crystal_armor_boots", CrystalArmorItem.Boots::new);
		LAVA_STONE = REGISTRY.register("lava_stone", LavaStoneItem::new);
		LAVA_ARMOR_HELMET = REGISTRY.register("lava_armor_helmet", LavaArmorItem.Helmet::new);
		LAVA_ARMOR_CHESTPLATE = REGISTRY.register("lava_armor_chestplate", LavaArmorItem.Chestplate::new);
		LAVA_ARMOR_LEGGINGS = REGISTRY.register("lava_armor_leggings", LavaArmorItem.Leggings::new);
		LAVA_ARMOR_BOOTS = REGISTRY.register("lava_armor_boots", LavaArmorItem.Boots::new);
		RAIN_STONE = REGISTRY.register("rain_stone", RainStoneItem::new);
		TORNADO_STONE = REGISTRY.register("tornado_stone", TornadoStoneItem::new);
		OCEAN_STONE = REGISTRY.register("ocean_stone", OceanStoneItem::new);
		PLANTS_STONE = REGISTRY.register("plants_stone", PlantsStoneItem::new);
		ANIMALS_STONE = REGISTRY.register("animals_stone", AnimalsStoneItem::new);
		METAL_STONE = REGISTRY.register("metal_stone", MetalStoneItem::new);
		LIGHT_STONE = REGISTRY.register("light_stone", LightStoneItem::new);
		SHADOW_STONE = REGISTRY.register("shadow_stone", ShadowStoneItem::new);
		VACUUM_STONE = REGISTRY.register("vacuum_stone", VacuumStoneItem::new);
		SUN_STONE = REGISTRY.register("sun_stone", SunStoneItem::new);
		MOON_STONE = REGISTRY.register("moon_stone", MoonStoneItem::new);
		SPACE_STONE = REGISTRY.register("space_stone", SpaceStoneItem::new);
		TIME_STONE = REGISTRY.register("time_stone", TimeStoneItem::new);
		BLOOD_STONE = REGISTRY.register("blood_stone", BloodStoneItem::new);
		TECHNOLOGY_STONE = REGISTRY.register("technology_stone", TechnologyStoneItem::new);
		TELEPORTATION_STONE = REGISTRY.register("teleportation_stone", TeleportationStoneItem::new);
		EXPLOSION_STONE = REGISTRY.register("explosion_stone", ExplosionStoneItem::new);
		AMBER_STONE = REGISTRY.register("amber_stone", AmberStoneItem::new);
		CREATION_STONE = REGISTRY.register("creation_stone", CreationStoneItem::new);
		DESTRUCTION_STONE = REGISTRY.register("destruction_stone", DestructionStoneItem::new);
		MIST_STONE = REGISTRY.register("mist_stone", MistStoneItem::new);
		SAND_STONE = REGISTRY.register("sand_stone", SandStoneItem::new);
		SPEED_STONE = REGISTRY.register("speed_stone", SpeedStoneItem::new);
		POISON_STONE = REGISTRY.register("poison_stone", PoisonStoneItem::new);
		MAGNET_STONE = REGISTRY.register("magnet_stone", MagnetStoneItem::new);
		MUSHROOMS_STONE = REGISTRY.register("mushrooms_stone", MushroomsStoneItem::new);
		MERCURY_STONE = REGISTRY.register("mercury_stone", MercuryStoneItem::new);
		MUSIC_STONE = REGISTRY.register("music_stone", MusicStoneItem::new);
		PLAGUE_STONE = REGISTRY.register("plague_stone", PlagueStoneItem::new);
		BLUE_FLAME_STONE = REGISTRY.register("blue_flame_stone", BlueFlameStoneItem::new);
		GRAVITY_STONE = REGISTRY.register("gravity_stone", GravityStoneItem::new);
		SMOKE_STONE = REGISTRY.register("smoke_stone", SmokeStoneItem::new);
		FORM_STONE = REGISTRY.register("form_stone", FormStoneItem::new);
		MIND_STONE = REGISTRY.register("mind_stone", MindStoneItem::new);
		GOLDEN_DUST_STONE = REGISTRY.register("golden_dust_stone", GoldenDustStoneItem::new);
		DARKNESS_STONE = REGISTRY.register("darkness_stone", DarknessStoneItem::new);
		ENERGY_STONE = REGISTRY.register("energy_stone", EnergyStoneItem::new);
		SPIRIT_STONE = REGISTRY.register("spirit_stone", SpiritStoneItem::new);
		ICE_SPEAR = REGISTRY.register("ice_spear", IceSpearItem::new);
		RAIN_ARMOR_HELMET = REGISTRY.register("rain_armor_helmet", RainArmorItem.Helmet::new);
		RAIN_ARMOR_CHESTPLATE = REGISTRY.register("rain_armor_chestplate", RainArmorItem.Chestplate::new);
		RAIN_ARMOR_LEGGINGS = REGISTRY.register("rain_armor_leggings", RainArmorItem.Leggings::new);
		RAIN_ARMOR_BOOTS = REGISTRY.register("rain_armor_boots", RainArmorItem.Boots::new);
		TORNADO_ARMOR_HELMET = REGISTRY.register("tornado_armor_helmet", TornadoArmorItem.Helmet::new);
		TORNADO_ARMOR_CHESTPLATE = REGISTRY.register("tornado_armor_chestplate", TornadoArmorItem.Chestplate::new);
		TORNADO_ARMOR_LEGGINGS = REGISTRY.register("tornado_armor_leggings", TornadoArmorItem.Leggings::new);
		TORNADO_ARMOR_BOOTS = REGISTRY.register("tornado_armor_boots", TornadoArmorItem.Boots::new);
		OCEAN_ARMOR_HELMET = REGISTRY.register("ocean_armor_helmet", OceanArmorItem.Helmet::new);
		OCEAN_ARMOR_CHESTPLATE = REGISTRY.register("ocean_armor_chestplate", OceanArmorItem.Chestplate::new);
		OCEAN_ARMOR_LEGGINGS = REGISTRY.register("ocean_armor_leggings", OceanArmorItem.Leggings::new);
		OCEAN_ARMOR_BOOTS = REGISTRY.register("ocean_armor_boots", OceanArmorItem.Boots::new);
		PLANTS_ARMOR_HELMET = REGISTRY.register("plants_armor_helmet", PlantsArmorItem.Helmet::new);
		PLANTS_ARMOR_CHESTPLATE = REGISTRY.register("plants_armor_chestplate", PlantsArmorItem.Chestplate::new);
		PLANTS_ARMOR_LEGGINGS = REGISTRY.register("plants_armor_leggings", PlantsArmorItem.Leggings::new);
		PLANTS_ARMOR_BOOTS = REGISTRY.register("plants_armor_boots", PlantsArmorItem.Boots::new);
		ANIMALS_ARMOR_HELMET = REGISTRY.register("animals_armor_helmet", AnimalsArmorItem.Helmet::new);
		ANIMALS_ARMOR_CHESTPLATE = REGISTRY.register("animals_armor_chestplate", AnimalsArmorItem.Chestplate::new);
		ANIMALS_ARMOR_LEGGINGS = REGISTRY.register("animals_armor_leggings", AnimalsArmorItem.Leggings::new);
		ANIMALS_ARMOR_BOOTS = REGISTRY.register("animals_armor_boots", AnimalsArmorItem.Boots::new);
		METAL_ARMOR_HELMET = REGISTRY.register("metal_armor_helmet", MetalArmorItem.Helmet::new);
		METAL_ARMOR_CHESTPLATE = REGISTRY.register("metal_armor_chestplate", MetalArmorItem.Chestplate::new);
		METAL_ARMOR_LEGGINGS = REGISTRY.register("metal_armor_leggings", MetalArmorItem.Leggings::new);
		METAL_ARMOR_BOOTS = REGISTRY.register("metal_armor_boots", MetalArmorItem.Boots::new);
		LIGHTNING_FALCHION = REGISTRY.register("lightning_falchion", LightningFalchionItem::new);
		SOUND_DAGGER = REGISTRY.register("sound_dagger", SoundDaggerItem::new);
		CRYSTAL_KNIFE = REGISTRY.register("crystal_knife", CrystalKnifeItem::new);
		RAIN_BOW = REGISTRY.register("rain_bow", RainBowItem::new);
		LAVA_HAMMER = REGISTRY.register("lava_hammer", LavaHammerItem::new);
		TORNADO_AXE = REGISTRY.register("tornado_axe", TornadoAxeItem::new);
		OCEANIC_TRIDENT = REGISTRY.register("oceanic_trident", OceanicTridentItem::new);
		GREEN_STAFF = REGISTRY.register("green_staff", GreenStaffItem::new);
		ANIMALS_HALBERD = REGISTRY.register("animals_halberd", AnimalsHalberdItem::new);
		EMPTY_BATTERY = REGISTRY.register("empty_battery", EmptyBatteryItem::new);
		FIRE_BATTERY = REGISTRY.register("fire_battery", FireBatteryItem::new);
		AIR_BATTERY = REGISTRY.register("air_battery", AirBatteryItem::new);
		EARTH_BATTERY = REGISTRY.register("earth_battery", EarthBatteryItem::new);
		WATER_BATTERY = REGISTRY.register("water_battery", WaterBatteryItem::new);
		ETHER_BATTERY = REGISTRY.register("ether_battery", EtherBatteryItem::new);
		ICE_BATTERY = REGISTRY.register("ice_battery", IceBatteryItem::new);
		LIGHTNING_BATTERY = REGISTRY.register("lightning_battery", LightningBatteryItem::new);
		RIGHT_METAL_GAUNTLET = REGISTRY.register("right_metal_gauntlet", RightMetalGauntletItem::new);
		LEFT_METAL_GAUNTLET = REGISTRY.register("left_metal_gauntlet", LeftMetalGauntletItem::new);
		SOUND_BATTERY = REGISTRY.register("sound_battery", SoundBatteryItem::new);
		CRYSTAL_BATTERY = REGISTRY.register("crystal_battery", CrystalBatteryItem::new);
		LAVA_BATTERY = REGISTRY.register("lava_battery", LavaBatteryItem::new);
		RAIN_BATTERY = REGISTRY.register("rain_battery", RainBatteryItem::new);
		TORNADO_BATTERY = REGISTRY.register("tornado_battery", TornadoBatteryItem::new);
		OCEAN_BATTERY = REGISTRY.register("ocean_battery", OceanBatteryItem::new);
		PLANTS_BATTERY = REGISTRY.register("plants_battery", PlantsBatteryItem::new);
		ANIMALS_BATTERY = REGISTRY.register("animals_battery", AnimalsBatteryItem::new);
		METAL_BATTERY = REGISTRY.register("metal_battery", MetalBatteryItem::new);
		LIGHT_ARMOR_HELMET = REGISTRY.register("light_armor_helmet", LightArmorItem.Helmet::new);
		LIGHT_ARMOR_CHESTPLATE = REGISTRY.register("light_armor_chestplate", LightArmorItem.Chestplate::new);
		LIGHT_ARMOR_LEGGINGS = REGISTRY.register("light_armor_leggings", LightArmorItem.Leggings::new);
		LIGHT_ARMOR_BOOTS = REGISTRY.register("light_armor_boots", LightArmorItem.Boots::new);
		LIGHT_BATTERY = REGISTRY.register("light_battery", LightBatteryItem::new);
		LIGHT_SWORD = REGISTRY.register("light_sword", LightSwordItem::new);
		SHADOW_ARMOR_HELMET = REGISTRY.register("shadow_armor_helmet", ShadowArmorItem.Helmet::new);
		SHADOW_ARMOR_CHESTPLATE = REGISTRY.register("shadow_armor_chestplate", ShadowArmorItem.Chestplate::new);
		SHADOW_ARMOR_LEGGINGS = REGISTRY.register("shadow_armor_leggings", ShadowArmorItem.Leggings::new);
		SHADOW_ARMOR_BOOTS = REGISTRY.register("shadow_armor_boots", ShadowArmorItem.Boots::new);
		SHADOW_BATTERY = REGISTRY.register("shadow_battery", ShadowBatteryItem::new);
		DEPLETED_ENERGIUM_INGOT = REGISTRY.register("depleted_energium_ingot", DepletedEnergiumIngotItem::new);
		DEPLETED_ENERGIUM_ORE = block(PowerModBlocks.DEPLETED_ENERGIUM_ORE);
		DEPLETED_ENERGIUM_BLOCK = block(PowerModBlocks.DEPLETED_ENERGIUM_BLOCK);
		RAW_DEPLETED_ENERGIUM = REGISTRY.register("raw_depleted_energium", RawDepletedEnergiumItem::new);
		ENERGIUM_INGOT = REGISTRY.register("energium_ingot", EnergiumIngotItem::new);
		ENERGIUM_BLOCK = block(PowerModBlocks.ENERGIUM_BLOCK);
		SHADOW_SCYTHE = REGISTRY.register("shadow_scythe", ShadowScytheItem::new);
		VACUUM_ARMOR_HELMET = REGISTRY.register("vacuum_armor_helmet", VacuumArmorItem.Helmet::new);
		VACUUM_ARMOR_CHESTPLATE = REGISTRY.register("vacuum_armor_chestplate", VacuumArmorItem.Chestplate::new);
		VACUUM_ARMOR_LEGGINGS = REGISTRY.register("vacuum_armor_leggings", VacuumArmorItem.Leggings::new);
		VACUUM_ARMOR_BOOTS = REGISTRY.register("vacuum_armor_boots", VacuumArmorItem.Boots::new);
		VACUUM_BATTERY = REGISTRY.register("vacuum_battery", VacuumBatteryItem::new);
		BATTERY_CHARGER = block(PowerModBlocks.BATTERY_CHARGER);
		VACUUM_DAGGER = REGISTRY.register("vacuum_dagger", VacuumDaggerItem::new);
		ENERGIUM_UPGRADE_SMITHING_TEMPLATE = REGISTRY.register("energium_upgrade_smithing_template", EnergiumUpgradeSmithingTemplateItem::new);
		ENERGIUM_PICKAXE = REGISTRY.register("energium_pickaxe", EnergiumPickaxeItem::new);
		ENERGIUM_AXE = REGISTRY.register("energium_axe", EnergiumAxeItem::new);
		ENERGIUM_SWORD = REGISTRY.register("energium_sword", EnergiumSwordItem::new);
		ENERGIUM_SHOVEL = REGISTRY.register("energium_shovel", EnergiumShovelItem::new);
		ENERGIUM_HOE = REGISTRY.register("energium_hoe", EnergiumHoeItem::new);
		ENERGIUM_ARMOR_HELMET = REGISTRY.register("energium_armor_helmet", EnergiumArmorItem.Helmet::new);
		ENERGIUM_ARMOR_CHESTPLATE = REGISTRY.register("energium_armor_chestplate", EnergiumArmorItem.Chestplate::new);
		ENERGIUM_ARMOR_LEGGINGS = REGISTRY.register("energium_armor_leggings", EnergiumArmorItem.Leggings::new);
		ENERGIUM_ARMOR_BOOTS = REGISTRY.register("energium_armor_boots", EnergiumArmorItem.Boots::new);
		ENERGY_ARMOR_HELMET = REGISTRY.register("energy_armor_helmet", EnergyArmorItem.Helmet::new);
		ENERGY_ARMOR_CHESTPLATE = REGISTRY.register("energy_armor_chestplate", EnergyArmorItem.Chestplate::new);
		ENERGY_ARMOR_LEGGINGS = REGISTRY.register("energy_armor_leggings", EnergyArmorItem.Leggings::new);
		ENERGY_ARMOR_BOOTS = REGISTRY.register("energy_armor_boots", EnergyArmorItem.Boots::new);
		ENERGY_BATTERY = REGISTRY.register("energy_battery", EnergyBatteryItem::new);
		ENERGIUM_CORE = REGISTRY.register("energium_core", EnergiumCoreItem::new);
		ENERGY_STAFF = REGISTRY.register("energy_staff", EnergyStaffItem::new);
		KEEPERS_BOX = block(PowerModBlocks.KEEPERS_BOX);
		SUN_ARMOR_HELMET = REGISTRY.register("sun_armor_helmet", SunArmorItem.Helmet::new);
		SUN_ARMOR_CHESTPLATE = REGISTRY.register("sun_armor_chestplate", SunArmorItem.Chestplate::new);
		SUN_ARMOR_LEGGINGS = REGISTRY.register("sun_armor_leggings", SunArmorItem.Leggings::new);
		SUN_ARMOR_BOOTS = REGISTRY.register("sun_armor_boots", SunArmorItem.Boots::new);
		SUN_BATTERY = REGISTRY.register("sun_battery", SunBatteryItem::new);
		SOLAR_BLADE = REGISTRY.register("solar_blade", SolarBladeItem::new);
		MOON_ARMOR_HELMET = REGISTRY.register("moon_armor_helmet", MoonArmorItem.Helmet::new);
		MOON_ARMOR_CHESTPLATE = REGISTRY.register("moon_armor_chestplate", MoonArmorItem.Chestplate::new);
		MOON_ARMOR_LEGGINGS = REGISTRY.register("moon_armor_leggings", MoonArmorItem.Leggings::new);
		MOON_ARMOR_BOOTS = REGISTRY.register("moon_armor_boots", MoonArmorItem.Boots::new);
		MOON_BATTERY = REGISTRY.register("moon_battery", MoonBatteryItem::new);
		MOON_DOUBLE_SIDED_SPEAR = REGISTRY.register("moon_double_sided_spear", MoonDoubleSidedSpearItem::new);
		MOON_BLOCK = block(PowerModBlocks.MOON_BLOCK);
		SPACE_ARMOR_HELMET = REGISTRY.register("space_armor_helmet", SpaceArmorItem.Helmet::new);
		SPACE_ARMOR_CHESTPLATE = REGISTRY.register("space_armor_chestplate", SpaceArmorItem.Chestplate::new);
		SPACE_ARMOR_LEGGINGS = REGISTRY.register("space_armor_leggings", SpaceArmorItem.Leggings::new);
		SPACE_ARMOR_BOOTS = REGISTRY.register("space_armor_boots", SpaceArmorItem.Boots::new);
		SPACE_BATTERY = REGISTRY.register("space_battery", SpaceBatteryItem::new);
		CONSTELLATION_SWORD = REGISTRY.register("constellation_sword", ConstellationSwordItem::new);
		TIME_ARMOR_HELMET = REGISTRY.register("time_armor_helmet", TimeArmorItem.Helmet::new);
		TIME_ARMOR_CHESTPLATE = REGISTRY.register("time_armor_chestplate", TimeArmorItem.Chestplate::new);
		TIME_ARMOR_LEGGINGS = REGISTRY.register("time_armor_leggings", TimeArmorItem.Leggings::new);
		TIME_ARMOR_BOOTS = REGISTRY.register("time_armor_boots", TimeArmorItem.Boots::new);
		TIME_BATTERY = REGISTRY.register("time_battery", TimeBatteryItem::new);
		TIME_KHOPESH = REGISTRY.register("time_khopesh", TimeKhopeshItem::new);
		CREATION_ARMOR_HELMET = REGISTRY.register("creation_armor_helmet", CreationArmorItem.Helmet::new);
		CREATION_ARMOR_CHESTPLATE = REGISTRY.register("creation_armor_chestplate", CreationArmorItem.Chestplate::new);
		CREATION_ARMOR_LEGGINGS = REGISTRY.register("creation_armor_leggings", CreationArmorItem.Leggings::new);
		CREATION_ARMOR_BOOTS = REGISTRY.register("creation_armor_boots", CreationArmorItem.Boots::new);
		CREATION_BATTERY = REGISTRY.register("creation_battery", CreationBatteryItem::new);
		ENERGIUM_CONTROLLER = block(PowerModBlocks.ENERGIUM_CONTROLLER);
		CREATION_STAFF = REGISTRY.register("creation_staff", CreationStaffItem::new);
		AMPLIFIER_ORE = block(PowerModBlocks.AMPLIFIER_ORE);
		AMPLIFIER_DROP = REGISTRY.register("amplifier_drop", AmplifierDropItem::new);
		RAW_AMPLIFIER = REGISTRY.register("raw_amplifier", RawAmplifierItem::new);
		CREATION_SWORD = REGISTRY.register("creation_sword", CreationSwordItem::new);
		CREATION_PICKAXE = REGISTRY.register("creation_pickaxe", CreationPickaxeItem::new);
		CREATION_AXE = REGISTRY.register("creation_axe", CreationAxeItem::new);
		CREATION_HOE = REGISTRY.register("creation_hoe", CreationHoeItem::new);
		CREATION_SHOVEL = REGISTRY.register("creation_shovel", CreationShovelItem::new);
		DESTRUCTION_ARMOR_HELMET = REGISTRY.register("destruction_armor_helmet", DestructionArmorItem.Helmet::new);
		DESTRUCTION_ARMOR_CHESTPLATE = REGISTRY.register("destruction_armor_chestplate", DestructionArmorItem.Chestplate::new);
		DESTRUCTION_ARMOR_LEGGINGS = REGISTRY.register("destruction_armor_leggings", DestructionArmorItem.Leggings::new);
		DESTRUCTION_ARMOR_BOOTS = REGISTRY.register("destruction_armor_boots", DestructionArmorItem.Boots::new);
		DESTRUCTION_BATTERY = REGISTRY.register("destruction_battery", DestructionBatteryItem::new);
		DESTRUCTION_BROADSWORD = REGISTRY.register("destruction_broadsword", DestructionBroadswordItem::new);
		AMPLIFIER_BLOCK = block(PowerModBlocks.AMPLIFIER_BLOCK);
		BLOOD_ARMOR_HELMET = REGISTRY.register("blood_armor_helmet", BloodArmorItem.Helmet::new);
		BLOOD_ARMOR_CHESTPLATE = REGISTRY.register("blood_armor_chestplate", BloodArmorItem.Chestplate::new);
		BLOOD_ARMOR_LEGGINGS = REGISTRY.register("blood_armor_leggings", BloodArmorItem.Leggings::new);
		BLOOD_ARMOR_BOOTS = REGISTRY.register("blood_armor_boots", BloodArmorItem.Boots::new);
		BLOOD_SICKLE = REGISTRY.register("blood_sickle", BloodSickleItem::new);
		BLOOD_BATTERY = REGISTRY.register("blood_battery", BloodBatteryItem::new);
		RAW_DEPLETED_ENERGIUM_BLOCK = block(PowerModBlocks.RAW_DEPLETED_ENERGIUM_BLOCK);
		RAW_AMPLIFIER_BLOCK = block(PowerModBlocks.RAW_AMPLIFIER_BLOCK);
		TECHNOLOGY_ARMOR_HELMET = REGISTRY.register("technology_armor_helmet", TechnologyArmorItem.Helmet::new);
		TECHNOLOGY_ARMOR_CHESTPLATE = REGISTRY.register("technology_armor_chestplate", TechnologyArmorItem.Chestplate::new);
		TECHNOLOGY_ARMOR_LEGGINGS = REGISTRY.register("technology_armor_leggings", TechnologyArmorItem.Leggings::new);
		TECHNOLOGY_ARMOR_BOOTS = REGISTRY.register("technology_armor_boots", TechnologyArmorItem.Boots::new);
		TECHNOLOGY_BATTERY = REGISTRY.register("technology_battery", TechnologyBatteryItem::new);
		TELEPORTATION_ARMOR_HELMET = REGISTRY.register("teleportation_armor_helmet", TeleportationArmorItem.Helmet::new);
		TELEPORTATION_ARMOR_CHESTPLATE = REGISTRY.register("teleportation_armor_chestplate", TeleportationArmorItem.Chestplate::new);
		TELEPORTATION_ARMOR_LEGGINGS = REGISTRY.register("teleportation_armor_leggings", TeleportationArmorItem.Leggings::new);
		TELEPORTATION_ARMOR_BOOTS = REGISTRY.register("teleportation_armor_boots", TeleportationArmorItem.Boots::new);
		TECHNO_PICKAXE = REGISTRY.register("techno_pickaxe", TechnoPickaxeItem::new);
		TELEPORTATION_BATTERY = REGISTRY.register("teleportation_battery", TeleportationBatteryItem::new);
		BLUE_PORTAL = block(PowerModBlocks.BLUE_PORTAL);
		ORANGE_PORTAL = block(PowerModBlocks.ORANGE_PORTAL);
		EXPLOSION_ARMOR_HELMET = REGISTRY.register("explosion_armor_helmet", ExplosionArmorItem.Helmet::new);
		EXPLOSION_ARMOR_CHESTPLATE = REGISTRY.register("explosion_armor_chestplate", ExplosionArmorItem.Chestplate::new);
		EXPLOSION_ARMOR_LEGGINGS = REGISTRY.register("explosion_armor_leggings", ExplosionArmorItem.Leggings::new);
		EXPLOSION_ARMOR_BOOTS = REGISTRY.register("explosion_armor_boots", ExplosionArmorItem.Boots::new);
		EXPLOSION_BATTERY = REGISTRY.register("explosion_battery", ExplosionBatteryItem::new);
		EXPLOSION_MACE = REGISTRY.register("explosion_mace", ExplosionMaceItem::new);
		AMBER_ARMOR_HELMET = REGISTRY.register("amber_armor_helmet", AmberArmorItem.Helmet::new);
		AMBER_ARMOR_CHESTPLATE = REGISTRY.register("amber_armor_chestplate", AmberArmorItem.Chestplate::new);
		AMBER_ARMOR_LEGGINGS = REGISTRY.register("amber_armor_leggings", AmberArmorItem.Leggings::new);
		AMBER_ARMOR_BOOTS = REGISTRY.register("amber_armor_boots", AmberArmorItem.Boots::new);
		AMBER_BATTERY = REGISTRY.register("amber_battery", AmberBatteryItem::new);
		AMBER_STAFF = REGISTRY.register("amber_staff", AmberStaffItem::new);
		AMBER_BLOCK = block(PowerModBlocks.AMBER_BLOCK);
		AMPLIFIER_RING = REGISTRY.register("amplifier_ring", AmplifierRingItem::new);
		CURSED_STONE = block(PowerModBlocks.CURSED_STONE);
		CURSED_STONE_BRICKS = block(PowerModBlocks.CURSED_STONE_BRICKS);
		CURSED_STONE_STAIRS = block(PowerModBlocks.CURSED_STONE_STAIRS);
		CURSED_STONE_SLAB = block(PowerModBlocks.CURSED_STONE_SLAB);
		CURSED_STONE_BRICKS_STAIRS = block(PowerModBlocks.CURSED_STONE_BRICKS_STAIRS);
		CURSED_STONE_BRICKS_SLAB = block(PowerModBlocks.CURSED_STONE_BRICKS_SLAB);
		CURSED_STONE_WALL = block(PowerModBlocks.CURSED_STONE_WALL);
		CURSED_STONE_BRICKS_WALL = block(PowerModBlocks.CURSED_STONE_BRICKS_WALL);
		POLISHED_CURSED_STONE = block(PowerModBlocks.POLISHED_CURSED_STONE);
		POLISHED_CURSED_STONE_STAIRS = block(PowerModBlocks.POLISHED_CURSED_STONE_STAIRS);
		POLISHED_CURSED_STONE_SLAB = block(PowerModBlocks.POLISHED_CURSED_STONE_SLAB);
		POLISHED_CURSED_STONE_WALL = block(PowerModBlocks.POLISHED_CURSED_STONE_WALL);
		CURSED_STONE_PILLAR = block(PowerModBlocks.CURSED_STONE_PILLAR);
		CURSED_LANTERN = block(PowerModBlocks.CURSED_LANTERN);
		COPYRIUM_INGOT = REGISTRY.register("copyrium_ingot", CopyriumIngotItem::new);
		COPYRIUM_ORE = block(PowerModBlocks.COPYRIUM_ORE);
		COPYRIUM_BLOCK = block(PowerModBlocks.COPYRIUM_BLOCK);
		RAW_COPYRIUM = REGISTRY.register("raw_copyrium", RawCopyriumItem::new);
		RAW_COPYRIUM_BLOCK = block(PowerModBlocks.RAW_COPYRIUM_BLOCK);
		ELEMENTAL_POWER_GENERATOR = block(PowerModBlocks.ELEMENTAL_POWER_GENERATOR);
		MIST_ARMOR_HELMET = REGISTRY.register("mist_armor_helmet", MistArmorItem.Helmet::new);
		MIST_ARMOR_CHESTPLATE = REGISTRY.register("mist_armor_chestplate", MistArmorItem.Chestplate::new);
		MIST_ARMOR_LEGGINGS = REGISTRY.register("mist_armor_leggings", MistArmorItem.Leggings::new);
		MIST_ARMOR_BOOTS = REGISTRY.register("mist_armor_boots", MistArmorItem.Boots::new);
		MIST_BATTERY = REGISTRY.register("mist_battery", MistBatteryItem::new);
		MISTY_FAN = REGISTRY.register("misty_fan", MistyFanItem::new);
		CURSED_VAULT = block(PowerModBlocks.CURSED_VAULT);
		CURSED_KEY = REGISTRY.register("cursed_key", CursedKeyItem::new);
		SAND_ARMOR_HELMET = REGISTRY.register("sand_armor_helmet", SandArmorItem.Helmet::new);
		SAND_ARMOR_CHESTPLATE = REGISTRY.register("sand_armor_chestplate", SandArmorItem.Chestplate::new);
		SAND_ARMOR_LEGGINGS = REGISTRY.register("sand_armor_leggings", SandArmorItem.Leggings::new);
		SAND_ARMOR_BOOTS = REGISTRY.register("sand_armor_boots", SandArmorItem.Boots::new);
		SAND_BATTERY = REGISTRY.register("sand_battery", SandBatteryItem::new);
		SAND_SABER = REGISTRY.register("sand_saber", SandSaberItem::new);
		SPEED_ARMOR_HELMET = REGISTRY.register("speed_armor_helmet", SpeedArmorItem.Helmet::new);
		SPEED_ARMOR_CHESTPLATE = REGISTRY.register("speed_armor_chestplate", SpeedArmorItem.Chestplate::new);
		SPEED_ARMOR_LEGGINGS = REGISTRY.register("speed_armor_leggings", SpeedArmorItem.Leggings::new);
		SPEED_ARMOR_BOOTS = REGISTRY.register("speed_armor_boots", SpeedArmorItem.Boots::new);
		SPEED_BATTERY = REGISTRY.register("speed_battery", SpeedBatteryItem::new);
		HIGHSPEED_DAGGER = REGISTRY.register("highspeed_dagger", HighspeedDaggerItem::new);
		POISON_ARMOR_HELMET = REGISTRY.register("poison_armor_helmet", PoisonArmorItem.Helmet::new);
		POISON_ARMOR_CHESTPLATE = REGISTRY.register("poison_armor_chestplate", PoisonArmorItem.Chestplate::new);
		POISON_ARMOR_LEGGINGS = REGISTRY.register("poison_armor_leggings", PoisonArmorItem.Leggings::new);
		POISON_ARMOR_BOOTS = REGISTRY.register("poison_armor_boots", PoisonArmorItem.Boots::new);
		POISON_BATTERY = REGISTRY.register("poison_battery", PoisonBatteryItem::new);
		POISON_BOW = REGISTRY.register("poison_bow", PoisonBowItem::new);
		MAGNET_ARMOR_HELMET = REGISTRY.register("magnet_armor_helmet", MagnetArmorItem.Helmet::new);
		MAGNET_ARMOR_CHESTPLATE = REGISTRY.register("magnet_armor_chestplate", MagnetArmorItem.Chestplate::new);
		MAGNET_ARMOR_LEGGINGS = REGISTRY.register("magnet_armor_leggings", MagnetArmorItem.Leggings::new);
		MAGNET_ARMOR_BOOTS = REGISTRY.register("magnet_armor_boots", MagnetArmorItem.Boots::new);
		MAGNET_BATTERY = REGISTRY.register("magnet_battery", MagnetBatteryItem::new);
		MAGNET_CLAWS = REGISTRY.register("magnet_claws", MagnetClawsItem::new);
		CURSED_LADDER = block(PowerModBlocks.CURSED_LADDER);
		CURSED_LAMP = block(PowerModBlocks.CURSED_LAMP);
		TELEPORTATION_BLADE = REGISTRY.register("teleportation_blade", TeleportationBladeItem::new);
		ENERGIUM_VAULT = block(PowerModBlocks.ENERGIUM_VAULT);
		ENERGIUM_KEY = REGISTRY.register("energium_key", EnergiumKeyItem::new);
		MUSHROOMS_ARMOR_HELMET = REGISTRY.register("mushrooms_armor_helmet", MushroomsArmorItem.Helmet::new);
		MUSHROOMS_ARMOR_CHESTPLATE = REGISTRY.register("mushrooms_armor_chestplate", MushroomsArmorItem.Chestplate::new);
		MUSHROOMS_ARMOR_LEGGINGS = REGISTRY.register("mushrooms_armor_leggings", MushroomsArmorItem.Leggings::new);
		MUSHROOMS_ARMOR_BOOTS = REGISTRY.register("mushrooms_armor_boots", MushroomsArmorItem.Boots::new);
		MUSHROOMS_BATTERY = REGISTRY.register("mushrooms_battery", MushroomsBatteryItem::new);
		MUSHROOMS_HAMMER = REGISTRY.register("mushrooms_hammer", MushroomsHammerItem::new);
		PURPLE_MUSHROOM = block(PowerModBlocks.PURPLE_MUSHROOM);
		MERCURY_ARMOR_HELMET = REGISTRY.register("mercury_armor_helmet", MercuryArmorItem.Helmet::new);
		MERCURY_ARMOR_CHESTPLATE = REGISTRY.register("mercury_armor_chestplate", MercuryArmorItem.Chestplate::new);
		MERCURY_ARMOR_LEGGINGS = REGISTRY.register("mercury_armor_leggings", MercuryArmorItem.Leggings::new);
		MERCURY_ARMOR_BOOTS = REGISTRY.register("mercury_armor_boots", MercuryArmorItem.Boots::new);
		LUCK_COIN = REGISTRY.register("luck_coin", LuckCoinItem::new);
		RAW_ENERGIUM = REGISTRY.register("raw_energium", RawEnergiumItem::new);
		ENERGIUM_ORE = block(PowerModBlocks.ENERGIUM_ORE);
		ENERGIUM_DUST = REGISTRY.register("energium_dust", EnergiumDustItem::new);
		RAW_ENERGIUM_BLOCK = block(PowerModBlocks.RAW_ENERGIUM_BLOCK);
		MERCURY_BATTERY = REGISTRY.register("mercury_battery", MercuryBatteryItem::new);
		MERCURY_BATTLE_AXE = REGISTRY.register("mercury_battle_axe", MercuryBattleAxeItem::new);
		DEEPSLATE_DEPLETED_ENERGIUM_ORE = block(PowerModBlocks.DEEPSLATE_DEPLETED_ENERGIUM_ORE);
		DEEPSLATE_ENERGIUM_ORE = block(PowerModBlocks.DEEPSLATE_ENERGIUM_ORE);
		DEEPSLATE_AMPLIFIER_ORE = block(PowerModBlocks.DEEPSLATE_AMPLIFIER_ORE);
		DEEPSLATE_COPYRIUM_ORE = block(PowerModBlocks.DEEPSLATE_COPYRIUM_ORE);
		MERCURY_BALL = REGISTRY.register("mercury_ball", MercuryBallItem::new);
		CHISELED_CURSED_STONE = block(PowerModBlocks.CHISELED_CURSED_STONE);
		CURSED_STONE_CRACKED_BRICKS = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS);
		CURSED_STONE_CRACKED_BRICKS_SLAB = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS_SLAB);
		CURSED_STONE_CRACKED_BRICKS_STAIRS = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS_STAIRS);
		CURSED_STONE_CRACKED_BRICKS_WALL = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS_WALL);
		MUSIC_ARMOR_HELMET = REGISTRY.register("music_armor_helmet", MusicArmorItem.Helmet::new);
		MUSIC_ARMOR_CHESTPLATE = REGISTRY.register("music_armor_chestplate", MusicArmorItem.Chestplate::new);
		MUSIC_ARMOR_LEGGINGS = REGISTRY.register("music_armor_leggings", MusicArmorItem.Leggings::new);
		MUSIC_ARMOR_BOOTS = REGISTRY.register("music_armor_boots", MusicArmorItem.Boots::new);
		MUSIC_BATTERY = REGISTRY.register("music_battery", MusicBatteryItem::new);
		MUSIC_GUITAR = REGISTRY.register("music_guitar", MusicGuitarItem::new);
		FREAKING_PARSNIP = REGISTRY.register("freaking_parsnip", FreakingParsnipItem::new);
		FREAKING_PARSNIP_BLOCK = block(PowerModBlocks.FREAKING_PARSNIP_BLOCK);
		FREAKING_PARSNIP_SOUP = REGISTRY.register("freaking_parsnip_soup", FreakingParsnipSoupItem::new);
		PLAGUE_ARMOR_HELMET = REGISTRY.register("plague_armor_helmet", PlagueArmorItem.Helmet::new);
		PLAGUE_ARMOR_CHESTPLATE = REGISTRY.register("plague_armor_chestplate", PlagueArmorItem.Chestplate::new);
		PLAGUE_ARMOR_LEGGINGS = REGISTRY.register("plague_armor_leggings", PlagueArmorItem.Leggings::new);
		PLAGUE_ARMOR_BOOTS = REGISTRY.register("plague_armor_boots", PlagueArmorItem.Boots::new);
		PLAGUE_BATTERY = REGISTRY.register("plague_battery", PlagueBatteryItem::new);
		PLAGUE_WALKING_STICK = REGISTRY.register("plague_walking_stick", PlagueWalkingStickItem::new);
		BLUE_FLAME_ARMOR_HELMET = REGISTRY.register("blue_flame_armor_helmet", BlueFlameArmorItem.Helmet::new);
		BLUE_FLAME_ARMOR_CHESTPLATE = REGISTRY.register("blue_flame_armor_chestplate", BlueFlameArmorItem.Chestplate::new);
		BLUE_FLAME_ARMOR_LEGGINGS = REGISTRY.register("blue_flame_armor_leggings", BlueFlameArmorItem.Leggings::new);
		BLUE_FLAME_ARMOR_BOOTS = REGISTRY.register("blue_flame_armor_boots", BlueFlameArmorItem.Boots::new);
		BLUE_FLAME_BATTERY = REGISTRY.register("blue_flame_battery", BlueFlameBatteryItem::new);
		BLUE_MAGIC_FIREBALL = REGISTRY.register("blue_magic_fireball", BlueMagicFireballItem::new);
		BLUE_FLAME_SWORD = REGISTRY.register("blue_flame_sword", BlueFlameSwordItem::new);
		GRAVITY_ARMOR_HELMET = REGISTRY.register("gravity_armor_helmet", GravityArmorItem.Helmet::new);
		GRAVITY_ARMOR_CHESTPLATE = REGISTRY.register("gravity_armor_chestplate", GravityArmorItem.Chestplate::new);
		GRAVITY_ARMOR_LEGGINGS = REGISTRY.register("gravity_armor_leggings", GravityArmorItem.Leggings::new);
		GRAVITY_ARMOR_BOOTS = REGISTRY.register("gravity_armor_boots", GravityArmorItem.Boots::new);
		GRAVITY_BATTERY = REGISTRY.register("gravity_battery", GravityBatteryItem::new);
		GRAVITY_MACE = REGISTRY.register("gravity_mace", GravityMaceItem::new);
		SMOKE_ARMOR_HELMET = REGISTRY.register("smoke_armor_helmet", SmokeArmorItem.Helmet::new);
		SMOKE_ARMOR_CHESTPLATE = REGISTRY.register("smoke_armor_chestplate", SmokeArmorItem.Chestplate::new);
		SMOKE_ARMOR_LEGGINGS = REGISTRY.register("smoke_armor_leggings", SmokeArmorItem.Leggings::new);
		SMOKE_ARMOR_BOOTS = REGISTRY.register("smoke_armor_boots", SmokeArmorItem.Boots::new);
		SMOKE_BATTERY = REGISTRY.register("smoke_battery", SmokeBatteryItem::new);
		SMOKE_MUSKET = REGISTRY.register("smoke_musket", SmokeMusketItem::new);
		SPIRIT_ARMOR_HELMET = REGISTRY.register("spirit_armor_helmet", SpiritArmorItem.Helmet::new);
		SPIRIT_ARMOR_CHESTPLATE = REGISTRY.register("spirit_armor_chestplate", SpiritArmorItem.Chestplate::new);
		SPIRIT_ARMOR_LEGGINGS = REGISTRY.register("spirit_armor_leggings", SpiritArmorItem.Leggings::new);
		SPIRIT_ARMOR_BOOTS = REGISTRY.register("spirit_armor_boots", SpiritArmorItem.Boots::new);
		SPIRIT_BATTERY = REGISTRY.register("spirit_battery", SpiritBatteryItem::new);
		SPIRIT_SICKLE = REGISTRY.register("spirit_sickle", SpiritSickleItem::new);
		FORM_ARMOR_HELMET = REGISTRY.register("form_armor_helmet", FormArmorItem.Helmet::new);
		FORM_ARMOR_CHESTPLATE = REGISTRY.register("form_armor_chestplate", FormArmorItem.Chestplate::new);
		FORM_ARMOR_LEGGINGS = REGISTRY.register("form_armor_leggings", FormArmorItem.Leggings::new);
		FORM_ARMOR_BOOTS = REGISTRY.register("form_armor_boots", FormArmorItem.Boots::new);
		FORM_BATTERY = REGISTRY.register("form_battery", FormBatteryItem::new);
		FORM_SAI = REGISTRY.register("form_sai", FormSaiItem::new);
		MIND_ARMOR_HELMET = REGISTRY.register("mind_armor_helmet", MindArmorItem.Helmet::new);
		MIND_ARMOR_CHESTPLATE = REGISTRY.register("mind_armor_chestplate", MindArmorItem.Chestplate::new);
		MIND_ARMOR_LEGGINGS = REGISTRY.register("mind_armor_leggings", MindArmorItem.Leggings::new);
		MIND_ARMOR_BOOTS = REGISTRY.register("mind_armor_boots", MindArmorItem.Boots::new);
		MIND_BATTERY = REGISTRY.register("mind_battery", MindBatteryItem::new);
		MIND_EPEE = REGISTRY.register("mind_epee", MindEpeeItem::new);
		GOLDEN_DUST_ARMOR_HELMET = REGISTRY.register("golden_dust_armor_helmet", GoldenDustArmorItem.Helmet::new);
		GOLDEN_DUST_ARMOR_CHESTPLATE = REGISTRY.register("golden_dust_armor_chestplate", GoldenDustArmorItem.Chestplate::new);
		GOLDEN_DUST_ARMOR_LEGGINGS = REGISTRY.register("golden_dust_armor_leggings", GoldenDustArmorItem.Leggings::new);
		GOLDEN_DUST_ARMOR_BOOTS = REGISTRY.register("golden_dust_armor_boots", GoldenDustArmorItem.Boots::new);
		GOLDEN_DUST_BATTERY = REGISTRY.register("golden_dust_battery", GoldenDustBatteryItem::new);
		GOLDEN_DUST_STAFF = REGISTRY.register("golden_dust_staff", GoldenDustStaffItem::new);
		DARKNESS_ARMOR_HELMET = REGISTRY.register("darkness_armor_helmet", DarknessArmorItem.Helmet::new);
		DARKNESS_ARMOR_CHESTPLATE = REGISTRY.register("darkness_armor_chestplate", DarknessArmorItem.Chestplate::new);
		DARKNESS_ARMOR_LEGGINGS = REGISTRY.register("darkness_armor_leggings", DarknessArmorItem.Leggings::new);
		DARKNESS_ARMOR_BOOTS = REGISTRY.register("darkness_armor_boots", DarknessArmorItem.Boots::new);
		DARKNESS_BATTERY = REGISTRY.register("darkness_battery", DarknessBatteryItem::new);
		DARK_SWORD = REGISTRY.register("dark_sword", DarkSwordItem::new);
		THIRST_ARMOR_HELMET = REGISTRY.register("thirst_armor_helmet", ThirstArmorItem.Helmet::new);
		THIRST_ARMOR_CHESTPLATE = REGISTRY.register("thirst_armor_chestplate", ThirstArmorItem.Chestplate::new);
		THIRST_ARMOR_LEGGINGS = REGISTRY.register("thirst_armor_leggings", ThirstArmorItem.Leggings::new);
		THIRST_ARMOR_BOOTS = REGISTRY.register("thirst_armor_boots", ThirstArmorItem.Boots::new);
		CHAOS_ARMOR_HELMET = REGISTRY.register("chaos_armor_helmet", ChaosArmorItem.Helmet::new);
		CHAOS_ARMOR_CHESTPLATE = REGISTRY.register("chaos_armor_chestplate", ChaosArmorItem.Chestplate::new);
		CHAOS_ARMOR_LEGGINGS = REGISTRY.register("chaos_armor_leggings", ChaosArmorItem.Leggings::new);
		CHAOS_ARMOR_BOOTS = REGISTRY.register("chaos_armor_boots", ChaosArmorItem.Boots::new);
		HORROR_ARMOR_HELMET = REGISTRY.register("horror_armor_helmet", HorrorArmorItem.Helmet::new);
		HORROR_ARMOR_CHESTPLATE = REGISTRY.register("horror_armor_chestplate", HorrorArmorItem.Chestplate::new);
		HORROR_ARMOR_LEGGINGS = REGISTRY.register("horror_armor_leggings", HorrorArmorItem.Leggings::new);
		HORROR_ARMOR_BOOTS = REGISTRY.register("horror_armor_boots", HorrorArmorItem.Boots::new);
		FILTH_ARMOR_HELMET = REGISTRY.register("filth_armor_helmet", FilthArmorItem.Helmet::new);
		FILTH_ARMOR_CHESTPLATE = REGISTRY.register("filth_armor_chestplate", FilthArmorItem.Chestplate::new);
		FILTH_ARMOR_LEGGINGS = REGISTRY.register("filth_armor_leggings", FilthArmorItem.Leggings::new);
		FILTH_ARMOR_BOOTS = REGISTRY.register("filth_armor_boots", FilthArmorItem.Boots::new);
		EMPTY_CHARACTERISTICS_CARD = REGISTRY.register("empty_characteristics_card", EmptyCharacteristicsCardItem::new);
		CHARACTERISTICS_CARD = REGISTRY.register("characteristics_card", CharacteristicsCardItem::new);
		MUSIC_DISC_CALL_OF_THE_PAST = REGISTRY.register("music_disc_call_of_the_past", MusicDiscCallOfThePastItem::new);
		MUSIC_DISC_ANCIENT_MOOD = REGISTRY.register("music_disc_ancient_mood", MusicDiscAncientMoodItem::new);
		CURSED_KNIGHT_SPAWN_EGG = REGISTRY.register("cursed_knight_spawn_egg", () -> new DeferredSpawnEggItem(PowerModEntities.CURSED_KNIGHT, -11447452, -9817013, new Item.Properties()));
		ENERGIUM_GOLEM_SPAWN_EGG = REGISTRY.register("energium_golem_spawn_egg", () -> new DeferredSpawnEggItem(PowerModEntities.ENERGIUM_GOLEM, -2242726, -8337805, new Item.Properties()));
		CURSED_SQUIRE_SPAWN_EGG = REGISTRY.register("cursed_squire_spawn_egg", () -> new DeferredSpawnEggItem(PowerModEntities.CURSED_SQUIRE, -11447452, -9817013, new Item.Properties()));
		CURSED_KEEPER_SPAWN_EGG = REGISTRY.register("cursed_keeper_spawn_egg", () -> new DeferredSpawnEggItem(PowerModEntities.CURSED_KEEPER, -9216650, -7256744, new Item.Properties()));
		KEEPERS_BOOK = REGISTRY.register("keepers_book", KeepersBookItem::new);
		RUNE_CUTTER = block(PowerModBlocks.RUNE_CUTTER);
		EXTRA_STAR_POINTS_RUNE_1 = REGISTRY.register("extra_star_points_rune_1", ExtraStarPointsRune1Item::new);
		EXTRA_STAR_POINTS_RUNE_2 = REGISTRY.register("extra_star_points_rune_2", ExtraStarPointsRune2Item::new);
		EXTRA_STAR_POINTS_RUNE_3 = REGISTRY.register("extra_star_points_rune_3", ExtraStarPointsRune3Item::new);
		MUSIC_HOPE = REGISTRY.register("music_hope", MusicHopeItem::new);
		ENERGIUM_SHIELD = REGISTRY.register("energium_shield", EnergiumShieldItem::new);
		REDUCED_STONE_RECHARGE_TIME_RUNE_1 = REGISTRY.register("reduced_stone_recharge_time_rune_1", ReducedStoneRechargeTimeRune1Item::new);
		REDUCED_STONE_RECHARGE_TIME_RUNE_2 = REGISTRY.register("reduced_stone_recharge_time_rune_2", ReducedStoneRechargeTimeRune2Item::new);
		REDUCED_STONE_RECHARGE_TIME_RUNE_3 = REGISTRY.register("reduced_stone_recharge_time_rune_3", ReducedStoneRechargeTimeRune3Item::new);
		ADDITION_TIME_MASTER_EFFECT_RUNE_1 = REGISTRY.register("addition_time_master_effect_rune_1", AdditionTimeMasterEffectRune1Item::new);
		ADDITION_TIME_MASTER_EFFECT_RUNE_2 = REGISTRY.register("addition_time_master_effect_rune_2", AdditionTimeMasterEffectRune2Item::new);
		ADDITION_TIME_MASTER_EFFECT_RUNE_3 = REGISTRY.register("addition_time_master_effect_rune_3", AdditionTimeMasterEffectRune3Item::new);
		HEAT_STONE = REGISTRY.register("heat_stone", HeatStoneItem::new);
		HEAT_ARMOR_HELMET = REGISTRY.register("heat_armor_helmet", HeatArmorItem.Helmet::new);
		HEAT_ARMOR_CHESTPLATE = REGISTRY.register("heat_armor_chestplate", HeatArmorItem.Chestplate::new);
		HEAT_ARMOR_LEGGINGS = REGISTRY.register("heat_armor_leggings", HeatArmorItem.Leggings::new);
		HEAT_ARMOR_BOOTS = REGISTRY.register("heat_armor_boots", HeatArmorItem.Boots::new);
		HEAT_KNIFE = REGISTRY.register("heat_knife", HeatKnifeItem::new);
		HEAT_BATTERY = REGISTRY.register("heat_battery", HeatBatteryItem::new);
		SHOCKWAVE_STONE = REGISTRY.register("shockwave_stone", ShockwaveStoneItem::new);
		SHOCKWAVE_ARMOR_HELMET = REGISTRY.register("shockwave_armor_helmet", ShockwaveArmorItem.Helmet::new);
		SHOCKWAVE_ARMOR_CHESTPLATE = REGISTRY.register("shockwave_armor_chestplate", ShockwaveArmorItem.Chestplate::new);
		SHOCKWAVE_ARMOR_LEGGINGS = REGISTRY.register("shockwave_armor_leggings", ShockwaveArmorItem.Leggings::new);
		SHOCKWAVE_ARMOR_BOOTS = REGISTRY.register("shockwave_armor_boots", ShockwaveArmorItem.Boots::new);
		SHOCKWAVE_GUN = REGISTRY.register("shockwave_gun", ShockwaveGunItem::new);
		SHOCKWAVE_BATTERY = REGISTRY.register("shockwave_battery", ShockwaveBatteryItem::new);
		PROTECTION_RUNE = REGISTRY.register("protection_rune", ProtectionRuneItem::new);
		SPIN_RUNE = REGISTRY.register("spin_rune", SpinRuneItem::new);
		DODGING_RUNE = REGISTRY.register("dodging_rune", DodgingRuneItem::new);
		INVISIBILITY_RUNE = REGISTRY.register("invisibility_rune", InvisibilityRuneItem::new);
		HEALING_RUNE = REGISTRY.register("healing_rune", HealingRuneItem::new);
		UNKNOWN_RUNE = REGISTRY.register("unknown_rune", UnknownRuneItem::new);
		CURSED_WORLD = REGISTRY.register("cursed_world", CursedWorldItem::new);
		COLORS_STONE = REGISTRY.register("colors_stone", ColorsStoneItem::new);
		COLORS_ARMOR_HELMET = REGISTRY.register("colors_armor_helmet", ColorsArmorItem.Helmet::new);
		COLORS_ARMOR_CHESTPLATE = REGISTRY.register("colors_armor_chestplate", ColorsArmorItem.Chestplate::new);
		COLORS_ARMOR_LEGGINGS = REGISTRY.register("colors_armor_leggings", ColorsArmorItem.Leggings::new);
		COLORS_ARMOR_BOOTS = REGISTRY.register("colors_armor_boots", ColorsArmorItem.Boots::new);
		COLORS_BATTERY = REGISTRY.register("colors_battery", ColorsBatteryItem::new);
		SPEAR_BRUSH = REGISTRY.register("spear_brush", SpearBrushItem::new);
		CURSED_GRASS_BLOCK = block(PowerModBlocks.CURSED_GRASS_BLOCK);
		CURSED_DIRT = block(PowerModBlocks.CURSED_DIRT);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(FIRE_STONE.get(), ResourceLocation.parse("power:fire_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(AIR_STONE.get(), ResourceLocation.parse("power:air_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(EARTH_STONE.get(), ResourceLocation.parse("power:earth_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(WATER_STONE.get(), ResourceLocation.parse("power:water_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(ETHER_STONE.get(), ResourceLocation.parse("power:ether_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(ICE_STONE.get(), ResourceLocation.parse("power:ice_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(LIGHTNING_STONE.get(), ResourceLocation.parse("power:lightning_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SOUND_STONE.get(), ResourceLocation.parse("power:sound_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(CRYSTAL_STONE.get(), ResourceLocation.parse("power:crystal_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(LAVA_STONE.get(), ResourceLocation.parse("power:lava_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(RAIN_STONE.get(), ResourceLocation.parse("power:rain_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(TORNADO_STONE.get(), ResourceLocation.parse("power:tornado_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(OCEAN_STONE.get(), ResourceLocation.parse("power:ocean_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(PLANTS_STONE.get(), ResourceLocation.parse("power:plants_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(ANIMALS_STONE.get(), ResourceLocation.parse("power:animals_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(METAL_STONE.get(), ResourceLocation.parse("power:metal_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(LIGHT_STONE.get(), ResourceLocation.parse("power:light_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SHADOW_STONE.get(), ResourceLocation.parse("power:shadow_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(VACUUM_STONE.get(), ResourceLocation.parse("power:vacuum_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SUN_STONE.get(), ResourceLocation.parse("power:sun_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MOON_STONE.get(), ResourceLocation.parse("power:moon_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SPACE_STONE.get(), ResourceLocation.parse("power:space_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(TIME_STONE.get(), ResourceLocation.parse("power:time_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(BLOOD_STONE.get(), ResourceLocation.parse("power:blood_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(TECHNOLOGY_STONE.get(), ResourceLocation.parse("power:technology_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(TELEPORTATION_STONE.get(), ResourceLocation.parse("power:teleportation_stone_recharge"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(EXPLOSION_STONE.get(), ResourceLocation.parse("power:explosion_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(AMBER_STONE.get(), ResourceLocation.parse("power:amber_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(CREATION_STONE.get(), ResourceLocation.parse("power:creation_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(DESTRUCTION_STONE.get(), ResourceLocation.parse("power:destruction_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MIST_STONE.get(), ResourceLocation.parse("power:mist_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SAND_STONE.get(), ResourceLocation.parse("power:sand_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SPEED_STONE.get(), ResourceLocation.parse("power:speed_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(POISON_STONE.get(), ResourceLocation.parse("power:poison_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MAGNET_STONE.get(), ResourceLocation.parse("power:magnet_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MUSHROOMS_STONE.get(), ResourceLocation.parse("power:mushrooms_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MERCURY_STONE.get(), ResourceLocation.parse("power:mercury_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MUSIC_STONE.get(), ResourceLocation.parse("power:music_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(PLAGUE_STONE.get(), ResourceLocation.parse("power:plague_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(BLUE_FLAME_STONE.get(), ResourceLocation.parse("power:blue_flame_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(GRAVITY_STONE.get(), ResourceLocation.parse("power:gravity_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SMOKE_STONE.get(), ResourceLocation.parse("power:smoke_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(FORM_STONE.get(), ResourceLocation.parse("power:form_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(MIND_STONE.get(), ResourceLocation.parse("power:mind_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(GOLDEN_DUST_STONE.get(), ResourceLocation.parse("power:golden_dust_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(DARKNESS_STONE.get(), ResourceLocation.parse("power:darkness_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(ENERGY_STONE.get(), ResourceLocation.parse("power:energy_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SPIRIT_STONE.get(), ResourceLocation.parse("power:spirit_stone_recharge"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(ENERGIUM_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(HEAT_STONE.get(), ResourceLocation.parse("power:heat_stone_rechage"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(SHOCKWAVE_STONE.get(), ResourceLocation.parse("power:shockwave_stone_rechage"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
				ItemProperties.register(COLORS_STONE.get(), ResourceLocation.parse("power:colors_stone_rechage"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) StoneGetRechargeStateProcedure.execute(itemStackToRender));
			});
		}
	}
}