
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.esmods.keepersofthestonestwo.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.client.event.RegisterRangeSelectItemModelPropertyEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;

import com.esmods.keepersofthestonestwo.item.WaterStoneItem;
import com.esmods.keepersofthestonestwo.item.WaterKatanaItem;
import com.esmods.keepersofthestonestwo.item.WaterBatteryItem;
import com.esmods.keepersofthestonestwo.item.WaterArmorItem;
import com.esmods.keepersofthestonestwo.item.VacuumStoneItem;
import com.esmods.keepersofthestonestwo.item.VacuumDaggerItem;
import com.esmods.keepersofthestonestwo.item.VacuumBatteryItem;
import com.esmods.keepersofthestonestwo.item.VacuumArmorItem;
import com.esmods.keepersofthestonestwo.item.TornadoStoneItem;
import com.esmods.keepersofthestonestwo.item.TornadoBatteryItem;
import com.esmods.keepersofthestonestwo.item.TornadoAxeItem;
import com.esmods.keepersofthestonestwo.item.TornadoArmorItem;
import com.esmods.keepersofthestonestwo.item.TimeStoneItem;
import com.esmods.keepersofthestonestwo.item.TimeKhopeshItem;
import com.esmods.keepersofthestonestwo.item.TimeBatteryItem;
import com.esmods.keepersofthestonestwo.item.TimeArmorItem;
import com.esmods.keepersofthestonestwo.item.ThirstArmorItem;
import com.esmods.keepersofthestonestwo.item.TeleportationStoneItem;
import com.esmods.keepersofthestonestwo.item.TeleportationBladeItem;
import com.esmods.keepersofthestonestwo.item.TeleportationBatteryItem;
import com.esmods.keepersofthestonestwo.item.TeleportationArmorItem;
import com.esmods.keepersofthestonestwo.item.TechnologyStoneItem;
import com.esmods.keepersofthestonestwo.item.TechnologyBatteryItem;
import com.esmods.keepersofthestonestwo.item.TechnologyArmorItem;
import com.esmods.keepersofthestonestwo.item.TechnoPickaxeItem;
import com.esmods.keepersofthestonestwo.item.SunStoneItem;
import com.esmods.keepersofthestonestwo.item.SunBatteryItem;
import com.esmods.keepersofthestonestwo.item.SunArmorItem;
import com.esmods.keepersofthestonestwo.item.SpiritStoneItem;
import com.esmods.keepersofthestonestwo.item.SpiritSickleItem;
import com.esmods.keepersofthestonestwo.item.SpiritBatteryItem;
import com.esmods.keepersofthestonestwo.item.SpiritArmorItem;
import com.esmods.keepersofthestonestwo.item.SpeedStoneItem;
import com.esmods.keepersofthestonestwo.item.SpeedBatteryItem;
import com.esmods.keepersofthestonestwo.item.SpeedArmorItem;
import com.esmods.keepersofthestonestwo.item.SpaceStoneItem;
import com.esmods.keepersofthestonestwo.item.SpaceBatteryItem;
import com.esmods.keepersofthestonestwo.item.SpaceArmorItem;
import com.esmods.keepersofthestonestwo.item.SoundStoneItem;
import com.esmods.keepersofthestonestwo.item.SoundDaggerItem;
import com.esmods.keepersofthestonestwo.item.SoundBatteryItem;
import com.esmods.keepersofthestonestwo.item.SoundArmorItem;
import com.esmods.keepersofthestonestwo.item.SolarBladeItem;
import com.esmods.keepersofthestonestwo.item.SmokeStoneItem;
import com.esmods.keepersofthestonestwo.item.SmokeMusketItem;
import com.esmods.keepersofthestonestwo.item.SmokeBatteryItem;
import com.esmods.keepersofthestonestwo.item.SmokeArmorItem;
import com.esmods.keepersofthestonestwo.item.ShadowStoneItem;
import com.esmods.keepersofthestonestwo.item.ShadowScytheItem;
import com.esmods.keepersofthestonestwo.item.ShadowBatteryItem;
import com.esmods.keepersofthestonestwo.item.ShadowArmorItem;
import com.esmods.keepersofthestonestwo.item.SandStoneItem;
import com.esmods.keepersofthestonestwo.item.SandSaberItem;
import com.esmods.keepersofthestonestwo.item.SandBatteryItem;
import com.esmods.keepersofthestonestwo.item.SandArmorItem;
import com.esmods.keepersofthestonestwo.item.RightMetalGauntletItem;
import com.esmods.keepersofthestonestwo.item.RawEnergiumItem;
import com.esmods.keepersofthestonestwo.item.RawDepletedEnergiumItem;
import com.esmods.keepersofthestonestwo.item.RawCopyriumItem;
import com.esmods.keepersofthestonestwo.item.RawAmplifierItem;
import com.esmods.keepersofthestonestwo.item.RainStoneItem;
import com.esmods.keepersofthestonestwo.item.RainBowItem;
import com.esmods.keepersofthestonestwo.item.RainBatteryItem;
import com.esmods.keepersofthestonestwo.item.RainArmorItem;
import com.esmods.keepersofthestonestwo.item.PoisonStoneItem;
import com.esmods.keepersofthestonestwo.item.PoisonBowItem;
import com.esmods.keepersofthestonestwo.item.PoisonBatteryItem;
import com.esmods.keepersofthestonestwo.item.PoisonArmorItem;
import com.esmods.keepersofthestonestwo.item.PlantsStoneItem;
import com.esmods.keepersofthestonestwo.item.PlantsBatteryItem;
import com.esmods.keepersofthestonestwo.item.PlantsArmorItem;
import com.esmods.keepersofthestonestwo.item.PlagueWalkingStickItem;
import com.esmods.keepersofthestonestwo.item.PlagueStoneItem;
import com.esmods.keepersofthestonestwo.item.PlagueBatteryItem;
import com.esmods.keepersofthestonestwo.item.PlagueArmorItem;
import com.esmods.keepersofthestonestwo.item.OceanicTridentItem;
import com.esmods.keepersofthestonestwo.item.OceanStoneItem;
import com.esmods.keepersofthestonestwo.item.OceanBatteryItem;
import com.esmods.keepersofthestonestwo.item.OceanArmorItem;
import com.esmods.keepersofthestonestwo.item.MusicStoneItem;
import com.esmods.keepersofthestonestwo.item.MusicGuitarItem;
import com.esmods.keepersofthestonestwo.item.MusicDiscCallOfThePastItem;
import com.esmods.keepersofthestonestwo.item.MusicDiscAncientMoodItem;
import com.esmods.keepersofthestonestwo.item.MusicBatteryItem;
import com.esmods.keepersofthestonestwo.item.MusicArmorItem;
import com.esmods.keepersofthestonestwo.item.MushroomsStoneItem;
import com.esmods.keepersofthestonestwo.item.MushroomsHammerItem;
import com.esmods.keepersofthestonestwo.item.MushroomsBatteryItem;
import com.esmods.keepersofthestonestwo.item.MushroomsArmorItem;
import com.esmods.keepersofthestonestwo.item.MoonStoneItem;
import com.esmods.keepersofthestonestwo.item.MoonDoubleSidedSpearItem;
import com.esmods.keepersofthestonestwo.item.MoonBatteryItem;
import com.esmods.keepersofthestonestwo.item.MoonArmorItem;
import com.esmods.keepersofthestonestwo.item.MistyFanItem;
import com.esmods.keepersofthestonestwo.item.MistStoneItem;
import com.esmods.keepersofthestonestwo.item.MistBatteryItem;
import com.esmods.keepersofthestonestwo.item.MistArmorItem;
import com.esmods.keepersofthestonestwo.item.MindStoneItem;
import com.esmods.keepersofthestonestwo.item.MindEpeeItem;
import com.esmods.keepersofthestonestwo.item.MindBatteryItem;
import com.esmods.keepersofthestonestwo.item.MindArmorItem;
import com.esmods.keepersofthestonestwo.item.MetalStoneItem;
import com.esmods.keepersofthestonestwo.item.MetalBatteryItem;
import com.esmods.keepersofthestonestwo.item.MetalArmorItem;
import com.esmods.keepersofthestonestwo.item.MercuryStoneItem;
import com.esmods.keepersofthestonestwo.item.MercuryBattleAxeItem;
import com.esmods.keepersofthestonestwo.item.MercuryBatteryItem;
import com.esmods.keepersofthestonestwo.item.MercuryBallItem;
import com.esmods.keepersofthestonestwo.item.MercuryArmorItem;
import com.esmods.keepersofthestonestwo.item.MagnetStoneItem;
import com.esmods.keepersofthestonestwo.item.MagnetClawsItem;
import com.esmods.keepersofthestonestwo.item.MagnetBatteryItem;
import com.esmods.keepersofthestonestwo.item.MagnetArmorItem;
import com.esmods.keepersofthestonestwo.item.MagicFireballItem;
import com.esmods.keepersofthestonestwo.item.LuckCoinItem;
import com.esmods.keepersofthestonestwo.item.LightningStoneItem;
import com.esmods.keepersofthestonestwo.item.LightningFalchionItem;
import com.esmods.keepersofthestonestwo.item.LightningBatteryItem;
import com.esmods.keepersofthestonestwo.item.LightningArmorItem;
import com.esmods.keepersofthestonestwo.item.LightSwordItem;
import com.esmods.keepersofthestonestwo.item.LightStoneItem;
import com.esmods.keepersofthestonestwo.item.LightBatteryItem;
import com.esmods.keepersofthestonestwo.item.LightArmorItem;
import com.esmods.keepersofthestonestwo.item.LeftMetalGauntletItem;
import com.esmods.keepersofthestonestwo.item.LavaStoneItem;
import com.esmods.keepersofthestonestwo.item.LavaHammerItem;
import com.esmods.keepersofthestonestwo.item.LavaBatteryItem;
import com.esmods.keepersofthestonestwo.item.LavaArmorItem;
import com.esmods.keepersofthestonestwo.item.IceStoneItem;
import com.esmods.keepersofthestonestwo.item.IceSpearItem;
import com.esmods.keepersofthestonestwo.item.IceBatteryItem;
import com.esmods.keepersofthestonestwo.item.IceArmorItem;
import com.esmods.keepersofthestonestwo.item.HorrorArmorItem;
import com.esmods.keepersofthestonestwo.item.HighspeedDaggerItem;
import com.esmods.keepersofthestonestwo.item.GreenStaffItem;
import com.esmods.keepersofthestonestwo.item.GravityStoneItem;
import com.esmods.keepersofthestonestwo.item.GravityMaceItem;
import com.esmods.keepersofthestonestwo.item.GravityBatteryItem;
import com.esmods.keepersofthestonestwo.item.GravityArmorItem;
import com.esmods.keepersofthestonestwo.item.GoldenDustStoneItem;
import com.esmods.keepersofthestonestwo.item.GoldenDustStaffItem;
import com.esmods.keepersofthestonestwo.item.GoldenDustBatteryItem;
import com.esmods.keepersofthestonestwo.item.GoldenDustArmorItem;
import com.esmods.keepersofthestonestwo.item.FreakingParsnipSoupItem;
import com.esmods.keepersofthestonestwo.item.FreakingParsnipItem;
import com.esmods.keepersofthestonestwo.item.FormStoneItem;
import com.esmods.keepersofthestonestwo.item.FormSaiItem;
import com.esmods.keepersofthestonestwo.item.FormBatteryItem;
import com.esmods.keepersofthestonestwo.item.FormArmorItem;
import com.esmods.keepersofthestonestwo.item.FireSwordItem;
import com.esmods.keepersofthestonestwo.item.FireStoneItem;
import com.esmods.keepersofthestonestwo.item.FireBatteryItem;
import com.esmods.keepersofthestonestwo.item.FireArmorItem;
import com.esmods.keepersofthestonestwo.item.FilthArmorItem;
import com.esmods.keepersofthestonestwo.item.ExplosionStoneItem;
import com.esmods.keepersofthestonestwo.item.ExplosionMaceItem;
import com.esmods.keepersofthestonestwo.item.ExplosionBatteryItem;
import com.esmods.keepersofthestonestwo.item.ExplosionArmorItem;
import com.esmods.keepersofthestonestwo.item.EtherStoneItem;
import com.esmods.keepersofthestonestwo.item.EtherGlaiveItem;
import com.esmods.keepersofthestonestwo.item.EtherBatteryItem;
import com.esmods.keepersofthestonestwo.item.EtherArmorItem;
import com.esmods.keepersofthestonestwo.item.EnergyStoneItem;
import com.esmods.keepersofthestonestwo.item.EnergyStaffItem;
import com.esmods.keepersofthestonestwo.item.EnergyBatteryItem;
import com.esmods.keepersofthestonestwo.item.EnergyArmorItem;
import com.esmods.keepersofthestonestwo.item.EnergiumUpgradeSmithingTemplateItem;
import com.esmods.keepersofthestonestwo.item.EnergiumSwordItem;
import com.esmods.keepersofthestonestwo.item.EnergiumShovelItem;
import com.esmods.keepersofthestonestwo.item.EnergiumPickaxeItem;
import com.esmods.keepersofthestonestwo.item.EnergiumKeyItem;
import com.esmods.keepersofthestonestwo.item.EnergiumIngotItem;
import com.esmods.keepersofthestonestwo.item.EnergiumHoeItem;
import com.esmods.keepersofthestonestwo.item.EnergiumDustItem;
import com.esmods.keepersofthestonestwo.item.EnergiumCoreItem;
import com.esmods.keepersofthestonestwo.item.EnergiumAxeItem;
import com.esmods.keepersofthestonestwo.item.EnergiumArmorItem;
import com.esmods.keepersofthestonestwo.item.EmptyCharacteristicsCardItem;
import com.esmods.keepersofthestonestwo.item.EmptyBatteryItem;
import com.esmods.keepersofthestonestwo.item.EarthStoneItem;
import com.esmods.keepersofthestonestwo.item.EarthHammerItem;
import com.esmods.keepersofthestonestwo.item.EarthBatteryItem;
import com.esmods.keepersofthestonestwo.item.EarthArmorItem;
import com.esmods.keepersofthestonestwo.item.DestructionStoneItem;
import com.esmods.keepersofthestonestwo.item.DestructionBroadswordItem;
import com.esmods.keepersofthestonestwo.item.DestructionBatteryItem;
import com.esmods.keepersofthestonestwo.item.DestructionArmorItem;
import com.esmods.keepersofthestonestwo.item.DepletedEnergiumIngotItem;
import com.esmods.keepersofthestonestwo.item.DarknessStoneItem;
import com.esmods.keepersofthestonestwo.item.DarknessBatteryItem;
import com.esmods.keepersofthestonestwo.item.DarknessArmorItem;
import com.esmods.keepersofthestonestwo.item.DarkSwordItem;
import com.esmods.keepersofthestonestwo.item.CursedKeyItem;
import com.esmods.keepersofthestonestwo.item.CrystalStoneItem;
import com.esmods.keepersofthestonestwo.item.CrystalKnifeItem;
import com.esmods.keepersofthestonestwo.item.CrystalBatteryItem;
import com.esmods.keepersofthestonestwo.item.CrystalArmorItem;
import com.esmods.keepersofthestonestwo.item.CreationSwordItem;
import com.esmods.keepersofthestonestwo.item.CreationStoneItem;
import com.esmods.keepersofthestonestwo.item.CreationStaffItem;
import com.esmods.keepersofthestonestwo.item.CreationShovelItem;
import com.esmods.keepersofthestonestwo.item.CreationPickaxeItem;
import com.esmods.keepersofthestonestwo.item.CreationHoeItem;
import com.esmods.keepersofthestonestwo.item.CreationBatteryItem;
import com.esmods.keepersofthestonestwo.item.CreationAxeItem;
import com.esmods.keepersofthestonestwo.item.CreationArmorItem;
import com.esmods.keepersofthestonestwo.item.CopyriumIngotItem;
import com.esmods.keepersofthestonestwo.item.ConstellationSwordItem;
import com.esmods.keepersofthestonestwo.item.CharacteristicsCardItem;
import com.esmods.keepersofthestonestwo.item.ChaosArmorItem;
import com.esmods.keepersofthestonestwo.item.BlueMagicFireballItem;
import com.esmods.keepersofthestonestwo.item.BlueFlameSwordItem;
import com.esmods.keepersofthestonestwo.item.BlueFlameStoneItem;
import com.esmods.keepersofthestonestwo.item.BlueFlameBatteryItem;
import com.esmods.keepersofthestonestwo.item.BlueFlameArmorItem;
import com.esmods.keepersofthestonestwo.item.BloodStoneItem;
import com.esmods.keepersofthestonestwo.item.BloodSickleItem;
import com.esmods.keepersofthestonestwo.item.BloodBatteryItem;
import com.esmods.keepersofthestonestwo.item.BloodArmorItem;
import com.esmods.keepersofthestonestwo.item.AnimalsStoneItem;
import com.esmods.keepersofthestonestwo.item.AnimalsHalberdItem;
import com.esmods.keepersofthestonestwo.item.AnimalsBatteryItem;
import com.esmods.keepersofthestonestwo.item.AnimalsArmorItem;
import com.esmods.keepersofthestonestwo.item.AmplifierRingItem;
import com.esmods.keepersofthestonestwo.item.AmplifierDropItem;
import com.esmods.keepersofthestonestwo.item.AmberStoneItem;
import com.esmods.keepersofthestonestwo.item.AmberStaffItem;
import com.esmods.keepersofthestonestwo.item.AmberBatteryItem;
import com.esmods.keepersofthestonestwo.item.AmberArmorItem;
import com.esmods.keepersofthestonestwo.item.AirStoneItem;
import com.esmods.keepersofthestonestwo.item.AirRapierItem;
import com.esmods.keepersofthestonestwo.item.AirBatteryItem;
import com.esmods.keepersofthestonestwo.item.AirArmorItem;
import com.esmods.keepersofthestonestwo.PowerMod;

public class PowerModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(PowerMod.MODID);
	public static final DeferredItem<Item> FIRE_STONE = REGISTRY.registerItem("fire_stone", FireStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_STONE = REGISTRY.registerItem("air_stone", AirStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_STONE = REGISTRY.registerItem("earth_stone", EarthStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_STONE = REGISTRY.registerItem("water_stone", WaterStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_STONE = REGISTRY.registerItem("ether_stone", EtherStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> FIRE_ARMOR_HELMET = REGISTRY.registerItem("fire_armor_helmet", FireArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> FIRE_ARMOR_CHESTPLATE = REGISTRY.registerItem("fire_armor_chestplate", FireArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> FIRE_ARMOR_LEGGINGS = REGISTRY.registerItem("fire_armor_leggings", FireArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> FIRE_ARMOR_BOOTS = REGISTRY.registerItem("fire_armor_boots", FireArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> FIRE_SWORD = REGISTRY.registerItem("fire_sword", FireSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_ARMOR_HELMET = REGISTRY.registerItem("air_armor_helmet", AirArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_ARMOR_CHESTPLATE = REGISTRY.registerItem("air_armor_chestplate", AirArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_ARMOR_LEGGINGS = REGISTRY.registerItem("air_armor_leggings", AirArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_ARMOR_BOOTS = REGISTRY.registerItem("air_armor_boots", AirArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_RAPIER = REGISTRY.registerItem("air_rapier", AirRapierItem::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_ARMOR_HELMET = REGISTRY.registerItem("earth_armor_helmet", EarthArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_ARMOR_CHESTPLATE = REGISTRY.registerItem("earth_armor_chestplate", EarthArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_ARMOR_LEGGINGS = REGISTRY.registerItem("earth_armor_leggings", EarthArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_ARMOR_BOOTS = REGISTRY.registerItem("earth_armor_boots", EarthArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_HAMMER = REGISTRY.registerItem("earth_hammer", EarthHammerItem::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_KATANA = REGISTRY.registerItem("water_katana", WaterKatanaItem::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_ARMOR_HELMET = REGISTRY.registerItem("water_armor_helmet", WaterArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_ARMOR_CHESTPLATE = REGISTRY.registerItem("water_armor_chestplate", WaterArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_ARMOR_LEGGINGS = REGISTRY.registerItem("water_armor_leggings", WaterArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_ARMOR_BOOTS = REGISTRY.registerItem("water_armor_boots", WaterArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_GLAIVE = REGISTRY.registerItem("ether_glaive", EtherGlaiveItem::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_ARMOR_HELMET = REGISTRY.registerItem("ether_armor_helmet", EtherArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_ARMOR_CHESTPLATE = REGISTRY.registerItem("ether_armor_chestplate", EtherArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_ARMOR_LEGGINGS = REGISTRY.registerItem("ether_armor_leggings", EtherArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_ARMOR_BOOTS = REGISTRY.registerItem("ether_armor_boots", EtherArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_STONE = REGISTRY.registerItem("ice_stone", IceStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_ARMOR_HELMET = REGISTRY.registerItem("ice_armor_helmet", IceArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_ARMOR_CHESTPLATE = REGISTRY.registerItem("ice_armor_chestplate", IceArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_ARMOR_LEGGINGS = REGISTRY.registerItem("ice_armor_leggings", IceArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_ARMOR_BOOTS = REGISTRY.registerItem("ice_armor_boots", IceArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_STONE = REGISTRY.registerItem("lightning_stone", LightningStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_ARMOR_HELMET = REGISTRY.registerItem("lightning_armor_helmet", LightningArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_ARMOR_CHESTPLATE = REGISTRY.registerItem("lightning_armor_chestplate", LightningArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_ARMOR_LEGGINGS = REGISTRY.registerItem("lightning_armor_leggings", LightningArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_ARMOR_BOOTS = REGISTRY.registerItem("lightning_armor_boots", LightningArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MAGIC_FIREBALL = REGISTRY.registerItem("magic_fireball", MagicFireballItem::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_STONE = REGISTRY.registerItem("sound_stone", SoundStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_ARMOR_HELMET = REGISTRY.registerItem("sound_armor_helmet", SoundArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_ARMOR_CHESTPLATE = REGISTRY.registerItem("sound_armor_chestplate", SoundArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_ARMOR_LEGGINGS = REGISTRY.registerItem("sound_armor_leggings", SoundArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_ARMOR_BOOTS = REGISTRY.registerItem("sound_armor_boots", SoundArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_STONE = REGISTRY.registerItem("crystal_stone", CrystalStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_ARMOR_HELMET = REGISTRY.registerItem("crystal_armor_helmet", CrystalArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_ARMOR_CHESTPLATE = REGISTRY.registerItem("crystal_armor_chestplate", CrystalArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_ARMOR_LEGGINGS = REGISTRY.registerItem("crystal_armor_leggings", CrystalArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_ARMOR_BOOTS = REGISTRY.registerItem("crystal_armor_boots", CrystalArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_STONE = REGISTRY.registerItem("lava_stone", LavaStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_ARMOR_HELMET = REGISTRY.registerItem("lava_armor_helmet", LavaArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_ARMOR_CHESTPLATE = REGISTRY.registerItem("lava_armor_chestplate", LavaArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_ARMOR_LEGGINGS = REGISTRY.registerItem("lava_armor_leggings", LavaArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_ARMOR_BOOTS = REGISTRY.registerItem("lava_armor_boots", LavaArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_STONE = REGISTRY.registerItem("rain_stone", RainStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_STONE = REGISTRY.registerItem("tornado_stone", TornadoStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> OCEAN_STONE = REGISTRY.registerItem("ocean_stone", OceanStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> PLANTS_STONE = REGISTRY.registerItem("plants_stone", PlantsStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_STONE = REGISTRY.registerItem("animals_stone", AnimalsStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> METAL_STONE = REGISTRY.registerItem("metal_stone", MetalStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_STONE = REGISTRY.registerItem("light_stone", LightStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SHADOW_STONE = REGISTRY.registerItem("shadow_stone", ShadowStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> VACUUM_STONE = REGISTRY.registerItem("vacuum_stone", VacuumStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SUN_STONE = REGISTRY.registerItem("sun_stone", SunStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_STONE = REGISTRY.registerItem("moon_stone", MoonStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SPACE_STONE = REGISTRY.registerItem("space_stone", SpaceStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_STONE = REGISTRY.registerItem("time_stone", TimeStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLOOD_STONE = REGISTRY.registerItem("blood_stone", BloodStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> TECHNOLOGY_STONE = REGISTRY.registerItem("technology_stone", TechnologyStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> TELEPORTATION_STONE = REGISTRY.registerItem("teleportation_stone", TeleportationStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> EXPLOSION_STONE = REGISTRY.registerItem("explosion_stone", ExplosionStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_STONE = REGISTRY.registerItem("amber_stone", AmberStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_STONE = REGISTRY.registerItem("creation_stone", CreationStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_STONE = REGISTRY.registerItem("destruction_stone", DestructionStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MIST_STONE = REGISTRY.registerItem("mist_stone", MistStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_STONE = REGISTRY.registerItem("sand_stone", SandStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SPEED_STONE = REGISTRY.registerItem("speed_stone", SpeedStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_STONE = REGISTRY.registerItem("poison_stone", PoisonStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_STONE = REGISTRY.registerItem("magnet_stone", MagnetStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_STONE = REGISTRY.registerItem("mushrooms_stone", MushroomsStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MERCURY_STONE = REGISTRY.registerItem("mercury_stone", MercuryStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_STONE = REGISTRY.registerItem("music_stone", MusicStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_STONE = REGISTRY.registerItem("plague_stone", PlagueStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_STONE = REGISTRY.registerItem("blue_flame_stone", BlueFlameStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_STONE = REGISTRY.registerItem("gravity_stone", GravityStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_STONE = REGISTRY.registerItem("smoke_stone", SmokeStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_STONE = REGISTRY.registerItem("form_stone", FormStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_STONE = REGISTRY.registerItem("mind_stone", MindStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_STONE = REGISTRY.registerItem("golden_dust_stone", GoldenDustStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> DARKNESS_STONE = REGISTRY.registerItem("darkness_stone", DarknessStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_STONE = REGISTRY.registerItem("energy_stone", EnergyStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_STONE = REGISTRY.registerItem("spirit_stone", SpiritStoneItem::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_SPEAR = REGISTRY.registerItem("ice_spear", IceSpearItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_ARMOR_HELMET = REGISTRY.registerItem("rain_armor_helmet", RainArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_ARMOR_CHESTPLATE = REGISTRY.registerItem("rain_armor_chestplate", RainArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_ARMOR_LEGGINGS = REGISTRY.registerItem("rain_armor_leggings", RainArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_ARMOR_BOOTS = REGISTRY.registerItem("rain_armor_boots", RainArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_ARMOR_HELMET = REGISTRY.registerItem("tornado_armor_helmet", TornadoArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_ARMOR_CHESTPLATE = REGISTRY.registerItem("tornado_armor_chestplate", TornadoArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_ARMOR_LEGGINGS = REGISTRY.registerItem("tornado_armor_leggings", TornadoArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_ARMOR_BOOTS = REGISTRY.registerItem("tornado_armor_boots", TornadoArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> OCEAN_ARMOR_HELMET = REGISTRY.registerItem("ocean_armor_helmet", OceanArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> OCEAN_ARMOR_CHESTPLATE = REGISTRY.registerItem("ocean_armor_chestplate", OceanArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> OCEAN_ARMOR_LEGGINGS = REGISTRY.registerItem("ocean_armor_leggings", OceanArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> OCEAN_ARMOR_BOOTS = REGISTRY.registerItem("ocean_armor_boots", OceanArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> PLANTS_ARMOR_HELMET = REGISTRY.registerItem("plants_armor_helmet", PlantsArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> PLANTS_ARMOR_CHESTPLATE = REGISTRY.registerItem("plants_armor_chestplate", PlantsArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> PLANTS_ARMOR_LEGGINGS = REGISTRY.registerItem("plants_armor_leggings", PlantsArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> PLANTS_ARMOR_BOOTS = REGISTRY.registerItem("plants_armor_boots", PlantsArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_ARMOR_HELMET = REGISTRY.registerItem("animals_armor_helmet", AnimalsArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_ARMOR_CHESTPLATE = REGISTRY.registerItem("animals_armor_chestplate", AnimalsArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_ARMOR_LEGGINGS = REGISTRY.registerItem("animals_armor_leggings", AnimalsArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_ARMOR_BOOTS = REGISTRY.registerItem("animals_armor_boots", AnimalsArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> METAL_ARMOR_HELMET = REGISTRY.registerItem("metal_armor_helmet", MetalArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> METAL_ARMOR_CHESTPLATE = REGISTRY.registerItem("metal_armor_chestplate", MetalArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> METAL_ARMOR_LEGGINGS = REGISTRY.registerItem("metal_armor_leggings", MetalArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> METAL_ARMOR_BOOTS = REGISTRY.registerItem("metal_armor_boots", MetalArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_FALCHION = REGISTRY.registerItem("lightning_falchion", LightningFalchionItem::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_DAGGER = REGISTRY.registerItem("sound_dagger", SoundDaggerItem::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_KNIFE = REGISTRY.registerItem("crystal_knife", CrystalKnifeItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_BOW = REGISTRY.registerItem("rain_bow", RainBowItem::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_HAMMER = REGISTRY.registerItem("lava_hammer", LavaHammerItem::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_AXE = REGISTRY.registerItem("tornado_axe", TornadoAxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> OCEANIC_TRIDENT = REGISTRY.registerItem("oceanic_trident", OceanicTridentItem::new, new Item.Properties());
	public static final DeferredItem<Item> GREEN_STAFF = REGISTRY.registerItem("green_staff", GreenStaffItem::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_HALBERD = REGISTRY.registerItem("animals_halberd", AnimalsHalberdItem::new, new Item.Properties());
	public static final DeferredItem<Item> EMPTY_BATTERY = REGISTRY.registerItem("empty_battery", EmptyBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> FIRE_BATTERY = REGISTRY.registerItem("fire_battery", FireBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> AIR_BATTERY = REGISTRY.registerItem("air_battery", AirBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> EARTH_BATTERY = REGISTRY.registerItem("earth_battery", EarthBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> WATER_BATTERY = REGISTRY.registerItem("water_battery", WaterBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> ETHER_BATTERY = REGISTRY.registerItem("ether_battery", EtherBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> ICE_BATTERY = REGISTRY.registerItem("ice_battery", IceBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHTNING_BATTERY = REGISTRY.registerItem("lightning_battery", LightningBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> RIGHT_METAL_GAUNTLET = REGISTRY.registerItem("right_metal_gauntlet", RightMetalGauntletItem::new, new Item.Properties());
	public static final DeferredItem<Item> LEFT_METAL_GAUNTLET = REGISTRY.registerItem("left_metal_gauntlet", LeftMetalGauntletItem::new, new Item.Properties());
	public static final DeferredItem<Item> SOUND_BATTERY = REGISTRY.registerItem("sound_battery", SoundBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> CRYSTAL_BATTERY = REGISTRY.registerItem("crystal_battery", CrystalBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> LAVA_BATTERY = REGISTRY.registerItem("lava_battery", LavaBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAIN_BATTERY = REGISTRY.registerItem("rain_battery", RainBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> TORNADO_BATTERY = REGISTRY.registerItem("tornado_battery", TornadoBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> OCEAN_BATTERY = REGISTRY.registerItem("ocean_battery", OceanBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> PLANTS_BATTERY = REGISTRY.registerItem("plants_battery", PlantsBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> ANIMALS_BATTERY = REGISTRY.registerItem("animals_battery", AnimalsBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> METAL_BATTERY = REGISTRY.registerItem("metal_battery", MetalBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_ARMOR_HELMET = REGISTRY.registerItem("light_armor_helmet", LightArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_ARMOR_CHESTPLATE = REGISTRY.registerItem("light_armor_chestplate", LightArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_ARMOR_LEGGINGS = REGISTRY.registerItem("light_armor_leggings", LightArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_ARMOR_BOOTS = REGISTRY.registerItem("light_armor_boots", LightArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_BATTERY = REGISTRY.registerItem("light_battery", LightBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> LIGHT_SWORD = REGISTRY.registerItem("light_sword", LightSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> SHADOW_ARMOR_HELMET = REGISTRY.registerItem("shadow_armor_helmet", ShadowArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SHADOW_ARMOR_CHESTPLATE = REGISTRY.registerItem("shadow_armor_chestplate", ShadowArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SHADOW_ARMOR_LEGGINGS = REGISTRY.registerItem("shadow_armor_leggings", ShadowArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SHADOW_ARMOR_BOOTS = REGISTRY.registerItem("shadow_armor_boots", ShadowArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SHADOW_BATTERY = REGISTRY.registerItem("shadow_battery", ShadowBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> DEPLETED_ENERGIUM_INGOT = REGISTRY.registerItem("depleted_energium_ingot", DepletedEnergiumIngotItem::new, new Item.Properties());
	public static final DeferredItem<Item> DEPLETED_ENERGIUM_ORE = block(PowerModBlocks.DEPLETED_ENERGIUM_ORE);
	public static final DeferredItem<Item> DEPLETED_ENERGIUM_BLOCK = block(PowerModBlocks.DEPLETED_ENERGIUM_BLOCK);
	public static final DeferredItem<Item> RAW_DEPLETED_ENERGIUM = REGISTRY.registerItem("raw_depleted_energium", RawDepletedEnergiumItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_INGOT = REGISTRY.registerItem("energium_ingot", EnergiumIngotItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_BLOCK = block(PowerModBlocks.ENERGIUM_BLOCK);
	public static final DeferredItem<Item> SHADOW_SCYTHE = REGISTRY.registerItem("shadow_scythe", ShadowScytheItem::new, new Item.Properties());
	public static final DeferredItem<Item> VACUUM_ARMOR_HELMET = REGISTRY.registerItem("vacuum_armor_helmet", VacuumArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> VACUUM_ARMOR_CHESTPLATE = REGISTRY.registerItem("vacuum_armor_chestplate", VacuumArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> VACUUM_ARMOR_LEGGINGS = REGISTRY.registerItem("vacuum_armor_leggings", VacuumArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> VACUUM_ARMOR_BOOTS = REGISTRY.registerItem("vacuum_armor_boots", VacuumArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> VACUUM_BATTERY = REGISTRY.registerItem("vacuum_battery", VacuumBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> BATTERY_CHARGER = block(PowerModBlocks.BATTERY_CHARGER);
	public static final DeferredItem<Item> VACUUM_DAGGER = REGISTRY.registerItem("vacuum_dagger", VacuumDaggerItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_UPGRADE_SMITHING_TEMPLATE = REGISTRY.registerItem("energium_upgrade_smithing_template", EnergiumUpgradeSmithingTemplateItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_PICKAXE = REGISTRY.registerItem("energium_pickaxe", EnergiumPickaxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_AXE = REGISTRY.registerItem("energium_axe", EnergiumAxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_SWORD = REGISTRY.registerItem("energium_sword", EnergiumSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_SHOVEL = REGISTRY.registerItem("energium_shovel", EnergiumShovelItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_HOE = REGISTRY.registerItem("energium_hoe", EnergiumHoeItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_ARMOR_HELMET = REGISTRY.registerItem("energium_armor_helmet", EnergiumArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_ARMOR_CHESTPLATE = REGISTRY.registerItem("energium_armor_chestplate", EnergiumArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_ARMOR_LEGGINGS = REGISTRY.registerItem("energium_armor_leggings", EnergiumArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_ARMOR_BOOTS = REGISTRY.registerItem("energium_armor_boots", EnergiumArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_ARMOR_HELMET = REGISTRY.registerItem("energy_armor_helmet", EnergyArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_ARMOR_CHESTPLATE = REGISTRY.registerItem("energy_armor_chestplate", EnergyArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_ARMOR_LEGGINGS = REGISTRY.registerItem("energy_armor_leggings", EnergyArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_ARMOR_BOOTS = REGISTRY.registerItem("energy_armor_boots", EnergyArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_BATTERY = REGISTRY.registerItem("energy_battery", EnergyBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_CORE = REGISTRY.registerItem("energium_core", EnergiumCoreItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGY_STAFF = REGISTRY.registerItem("energy_staff", EnergyStaffItem::new, new Item.Properties());
	public static final DeferredItem<Item> KEEPERS_BOX = block(PowerModBlocks.KEEPERS_BOX);
	public static final DeferredItem<Item> SUN_ARMOR_HELMET = REGISTRY.registerItem("sun_armor_helmet", SunArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SUN_ARMOR_CHESTPLATE = REGISTRY.registerItem("sun_armor_chestplate", SunArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SUN_ARMOR_LEGGINGS = REGISTRY.registerItem("sun_armor_leggings", SunArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SUN_ARMOR_BOOTS = REGISTRY.registerItem("sun_armor_boots", SunArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SUN_BATTERY = REGISTRY.registerItem("sun_battery", SunBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> SOLAR_BLADE = REGISTRY.registerItem("solar_blade", SolarBladeItem::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_ARMOR_HELMET = REGISTRY.registerItem("moon_armor_helmet", MoonArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_ARMOR_CHESTPLATE = REGISTRY.registerItem("moon_armor_chestplate", MoonArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_ARMOR_LEGGINGS = REGISTRY.registerItem("moon_armor_leggings", MoonArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_ARMOR_BOOTS = REGISTRY.registerItem("moon_armor_boots", MoonArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_BATTERY = REGISTRY.registerItem("moon_battery", MoonBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_DOUBLE_SIDED_SPEAR = REGISTRY.registerItem("moon_double_sided_spear", MoonDoubleSidedSpearItem::new, new Item.Properties());
	public static final DeferredItem<Item> MOON_BLOCK = block(PowerModBlocks.MOON_BLOCK);
	public static final DeferredItem<Item> SPACE_ARMOR_HELMET = REGISTRY.registerItem("space_armor_helmet", SpaceArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SPACE_ARMOR_CHESTPLATE = REGISTRY.registerItem("space_armor_chestplate", SpaceArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SPACE_ARMOR_LEGGINGS = REGISTRY.registerItem("space_armor_leggings", SpaceArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SPACE_ARMOR_BOOTS = REGISTRY.registerItem("space_armor_boots", SpaceArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SPACE_BATTERY = REGISTRY.registerItem("space_battery", SpaceBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> CONSTELLATION_SWORD = REGISTRY.registerItem("constellation_sword", ConstellationSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_ARMOR_HELMET = REGISTRY.registerItem("time_armor_helmet", TimeArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_ARMOR_CHESTPLATE = REGISTRY.registerItem("time_armor_chestplate", TimeArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_ARMOR_LEGGINGS = REGISTRY.registerItem("time_armor_leggings", TimeArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_ARMOR_BOOTS = REGISTRY.registerItem("time_armor_boots", TimeArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_BATTERY = REGISTRY.registerItem("time_battery", TimeBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> TIME_KHOPESH = REGISTRY.registerItem("time_khopesh", TimeKhopeshItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_ARMOR_HELMET = REGISTRY.registerItem("creation_armor_helmet", CreationArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_ARMOR_CHESTPLATE = REGISTRY.registerItem("creation_armor_chestplate", CreationArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_ARMOR_LEGGINGS = REGISTRY.registerItem("creation_armor_leggings", CreationArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_ARMOR_BOOTS = REGISTRY.registerItem("creation_armor_boots", CreationArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_BATTERY = REGISTRY.registerItem("creation_battery", CreationBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_CONTROLLER = block(PowerModBlocks.ENERGIUM_CONTROLLER);
	public static final DeferredItem<Item> CREATION_STAFF = REGISTRY.registerItem("creation_staff", CreationStaffItem::new, new Item.Properties());
	public static final DeferredItem<Item> AMPLIFIER_ORE = block(PowerModBlocks.AMPLIFIER_ORE);
	public static final DeferredItem<Item> AMPLIFIER_DROP = REGISTRY.registerItem("amplifier_drop", AmplifierDropItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAW_AMPLIFIER = REGISTRY.registerItem("raw_amplifier", RawAmplifierItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_SWORD = REGISTRY.registerItem("creation_sword", CreationSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_PICKAXE = REGISTRY.registerItem("creation_pickaxe", CreationPickaxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_AXE = REGISTRY.registerItem("creation_axe", CreationAxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_HOE = REGISTRY.registerItem("creation_hoe", CreationHoeItem::new, new Item.Properties());
	public static final DeferredItem<Item> CREATION_SHOVEL = REGISTRY.registerItem("creation_shovel", CreationShovelItem::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_HELMET = REGISTRY.registerItem("destruction_armor_helmet", DestructionArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_CHESTPLATE = REGISTRY.registerItem("destruction_armor_chestplate", DestructionArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_LEGGINGS = REGISTRY.registerItem("destruction_armor_leggings", DestructionArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_ARMOR_BOOTS = REGISTRY.registerItem("destruction_armor_boots", DestructionArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_BATTERY = REGISTRY.registerItem("destruction_battery", DestructionBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> DESTRUCTION_BROADSWORD = REGISTRY.registerItem("destruction_broadsword", DestructionBroadswordItem::new, new Item.Properties());
	public static final DeferredItem<Item> AMPLIFIER_BLOCK = block(PowerModBlocks.AMPLIFIER_BLOCK);
	public static final DeferredItem<Item> BLOOD_ARMOR_HELMET = REGISTRY.registerItem("blood_armor_helmet", BloodArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> BLOOD_ARMOR_CHESTPLATE = REGISTRY.registerItem("blood_armor_chestplate", BloodArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> BLOOD_ARMOR_LEGGINGS = REGISTRY.registerItem("blood_armor_leggings", BloodArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> BLOOD_ARMOR_BOOTS = REGISTRY.registerItem("blood_armor_boots", BloodArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> BLOOD_SICKLE = REGISTRY.registerItem("blood_sickle", BloodSickleItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLOOD_BATTERY = REGISTRY.registerItem("blood_battery", BloodBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAW_DEPLETED_ENERGIUM_BLOCK = block(PowerModBlocks.RAW_DEPLETED_ENERGIUM_BLOCK);
	public static final DeferredItem<Item> RAW_AMPLIFIER_BLOCK = block(PowerModBlocks.RAW_AMPLIFIER_BLOCK);
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_HELMET = REGISTRY.registerItem("technology_armor_helmet", TechnologyArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_CHESTPLATE = REGISTRY.registerItem("technology_armor_chestplate", TechnologyArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_LEGGINGS = REGISTRY.registerItem("technology_armor_leggings", TechnologyArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> TECHNOLOGY_ARMOR_BOOTS = REGISTRY.registerItem("technology_armor_boots", TechnologyArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> TECHNOLOGY_BATTERY = REGISTRY.registerItem("technology_battery", TechnologyBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_HELMET = REGISTRY.registerItem("teleportation_armor_helmet", TeleportationArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_CHESTPLATE = REGISTRY.registerItem("teleportation_armor_chestplate", TeleportationArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_LEGGINGS = REGISTRY.registerItem("teleportation_armor_leggings", TeleportationArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> TELEPORTATION_ARMOR_BOOTS = REGISTRY.registerItem("teleportation_armor_boots", TeleportationArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> TECHNO_PICKAXE = REGISTRY.registerItem("techno_pickaxe", TechnoPickaxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> TELEPORTATION_BATTERY = REGISTRY.registerItem("teleportation_battery", TeleportationBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_PORTAL = block(PowerModBlocks.BLUE_PORTAL);
	public static final DeferredItem<Item> ORANGE_PORTAL = block(PowerModBlocks.ORANGE_PORTAL);
	public static final DeferredItem<Item> EXPLOSION_ARMOR_HELMET = REGISTRY.registerItem("explosion_armor_helmet", ExplosionArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> EXPLOSION_ARMOR_CHESTPLATE = REGISTRY.registerItem("explosion_armor_chestplate", ExplosionArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> EXPLOSION_ARMOR_LEGGINGS = REGISTRY.registerItem("explosion_armor_leggings", ExplosionArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> EXPLOSION_ARMOR_BOOTS = REGISTRY.registerItem("explosion_armor_boots", ExplosionArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> EXPLOSION_BATTERY = REGISTRY.registerItem("explosion_battery", ExplosionBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> EXPLOSION_MACE = REGISTRY.registerItem("explosion_mace", ExplosionMaceItem::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_ARMOR_HELMET = REGISTRY.registerItem("amber_armor_helmet", AmberArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_ARMOR_CHESTPLATE = REGISTRY.registerItem("amber_armor_chestplate", AmberArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_ARMOR_LEGGINGS = REGISTRY.registerItem("amber_armor_leggings", AmberArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_ARMOR_BOOTS = REGISTRY.registerItem("amber_armor_boots", AmberArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_BATTERY = REGISTRY.registerItem("amber_battery", AmberBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_STAFF = REGISTRY.registerItem("amber_staff", AmberStaffItem::new, new Item.Properties());
	public static final DeferredItem<Item> AMBER_BLOCK = block(PowerModBlocks.AMBER_BLOCK);
	public static final DeferredItem<Item> AMPLIFIER_RING = REGISTRY.registerItem("amplifier_ring", AmplifierRingItem::new, new Item.Properties());
	public static final DeferredItem<Item> CURSED_STONE = block(PowerModBlocks.CURSED_STONE);
	public static final DeferredItem<Item> CURSED_STONE_BRICKS = block(PowerModBlocks.CURSED_STONE_BRICKS);
	public static final DeferredItem<Item> CURSED_STONE_STAIRS = block(PowerModBlocks.CURSED_STONE_STAIRS);
	public static final DeferredItem<Item> CURSED_STONE_SLAB = block(PowerModBlocks.CURSED_STONE_SLAB);
	public static final DeferredItem<Item> CURSED_STONE_BRICKS_STAIRS = block(PowerModBlocks.CURSED_STONE_BRICKS_STAIRS);
	public static final DeferredItem<Item> CURSED_STONE_BRICKS_SLAB = block(PowerModBlocks.CURSED_STONE_BRICKS_SLAB);
	public static final DeferredItem<Item> CURSED_STONE_WALL = block(PowerModBlocks.CURSED_STONE_WALL);
	public static final DeferredItem<Item> CURSED_STONE_BRICKS_WALL = block(PowerModBlocks.CURSED_STONE_BRICKS_WALL);
	public static final DeferredItem<Item> POLISHED_CURSED_STONE = block(PowerModBlocks.POLISHED_CURSED_STONE);
	public static final DeferredItem<Item> POLISHED_CURSED_STONE_STAIRS = block(PowerModBlocks.POLISHED_CURSED_STONE_STAIRS);
	public static final DeferredItem<Item> POLISHED_CURSED_STONE_SLAB = block(PowerModBlocks.POLISHED_CURSED_STONE_SLAB);
	public static final DeferredItem<Item> POLISHED_CURSED_STONE_WALL = block(PowerModBlocks.POLISHED_CURSED_STONE_WALL);
	public static final DeferredItem<Item> CURSED_STONE_PILLAR = block(PowerModBlocks.CURSED_STONE_PILLAR);
	public static final DeferredItem<Item> CURSED_LANTERN = block(PowerModBlocks.CURSED_LANTERN);
	public static final DeferredItem<Item> COPYRIUM_INGOT = REGISTRY.registerItem("copyrium_ingot", CopyriumIngotItem::new, new Item.Properties());
	public static final DeferredItem<Item> COPYRIUM_ORE = block(PowerModBlocks.COPYRIUM_ORE);
	public static final DeferredItem<Item> COPYRIUM_BLOCK = block(PowerModBlocks.COPYRIUM_BLOCK);
	public static final DeferredItem<Item> RAW_COPYRIUM = REGISTRY.registerItem("raw_copyrium", RawCopyriumItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAW_COPYRIUM_BLOCK = block(PowerModBlocks.RAW_COPYRIUM_BLOCK);
	public static final DeferredItem<Item> ELEMENTAL_POWER_GENERATOR = block(PowerModBlocks.ELEMENTAL_POWER_GENERATOR);
	public static final DeferredItem<Item> MIST_ARMOR_HELMET = REGISTRY.registerItem("mist_armor_helmet", MistArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MIST_ARMOR_CHESTPLATE = REGISTRY.registerItem("mist_armor_chestplate", MistArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MIST_ARMOR_LEGGINGS = REGISTRY.registerItem("mist_armor_leggings", MistArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MIST_ARMOR_BOOTS = REGISTRY.registerItem("mist_armor_boots", MistArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MIST_BATTERY = REGISTRY.registerItem("mist_battery", MistBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MISTY_FAN = REGISTRY.registerItem("misty_fan", MistyFanItem::new, new Item.Properties());
	public static final DeferredItem<Item> CURSED_VAULT = block(PowerModBlocks.CURSED_VAULT);
	public static final DeferredItem<Item> CURSED_KEY = REGISTRY.registerItem("cursed_key", CursedKeyItem::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_ARMOR_HELMET = REGISTRY.registerItem("sand_armor_helmet", SandArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_ARMOR_CHESTPLATE = REGISTRY.registerItem("sand_armor_chestplate", SandArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_ARMOR_LEGGINGS = REGISTRY.registerItem("sand_armor_leggings", SandArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_ARMOR_BOOTS = REGISTRY.registerItem("sand_armor_boots", SandArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_BATTERY = REGISTRY.registerItem("sand_battery", SandBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> SAND_SABER = REGISTRY.registerItem("sand_saber", SandSaberItem::new, new Item.Properties());
	public static final DeferredItem<Item> SPEED_ARMOR_HELMET = REGISTRY.registerItem("speed_armor_helmet", SpeedArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SPEED_ARMOR_CHESTPLATE = REGISTRY.registerItem("speed_armor_chestplate", SpeedArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SPEED_ARMOR_LEGGINGS = REGISTRY.registerItem("speed_armor_leggings", SpeedArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SPEED_ARMOR_BOOTS = REGISTRY.registerItem("speed_armor_boots", SpeedArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SPEED_BATTERY = REGISTRY.registerItem("speed_battery", SpeedBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> HIGHSPEED_DAGGER = REGISTRY.registerItem("highspeed_dagger", HighspeedDaggerItem::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_ARMOR_HELMET = REGISTRY.registerItem("poison_armor_helmet", PoisonArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_ARMOR_CHESTPLATE = REGISTRY.registerItem("poison_armor_chestplate", PoisonArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_ARMOR_LEGGINGS = REGISTRY.registerItem("poison_armor_leggings", PoisonArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_ARMOR_BOOTS = REGISTRY.registerItem("poison_armor_boots", PoisonArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_BATTERY = REGISTRY.registerItem("poison_battery", PoisonBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> POISON_BOW = REGISTRY.registerItem("poison_bow", PoisonBowItem::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_ARMOR_HELMET = REGISTRY.registerItem("magnet_armor_helmet", MagnetArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_ARMOR_CHESTPLATE = REGISTRY.registerItem("magnet_armor_chestplate", MagnetArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_ARMOR_LEGGINGS = REGISTRY.registerItem("magnet_armor_leggings", MagnetArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_ARMOR_BOOTS = REGISTRY.registerItem("magnet_armor_boots", MagnetArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_BATTERY = REGISTRY.registerItem("magnet_battery", MagnetBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MAGNET_CLAWS = REGISTRY.registerItem("magnet_claws", MagnetClawsItem::new, new Item.Properties());
	public static final DeferredItem<Item> CURSED_LADDER = block(PowerModBlocks.CURSED_LADDER);
	public static final DeferredItem<Item> CURSED_LAMP = block(PowerModBlocks.CURSED_LAMP);
	public static final DeferredItem<Item> TELEPORTATION_BLADE = REGISTRY.registerItem("teleportation_blade", TeleportationBladeItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_VAULT = block(PowerModBlocks.ENERGIUM_VAULT);
	public static final DeferredItem<Item> ENERGIUM_KEY = REGISTRY.registerItem("energium_key", EnergiumKeyItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_HELMET = REGISTRY.registerItem("mushrooms_armor_helmet", MushroomsArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_CHESTPLATE = REGISTRY.registerItem("mushrooms_armor_chestplate", MushroomsArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_LEGGINGS = REGISTRY.registerItem("mushrooms_armor_leggings", MushroomsArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_ARMOR_BOOTS = REGISTRY.registerItem("mushrooms_armor_boots", MushroomsArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_BATTERY = REGISTRY.registerItem("mushrooms_battery", MushroomsBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSHROOMS_HAMMER = REGISTRY.registerItem("mushrooms_hammer", MushroomsHammerItem::new, new Item.Properties());
	public static final DeferredItem<Item> PURPLE_MUSHROOM = block(PowerModBlocks.PURPLE_MUSHROOM);
	public static final DeferredItem<Item> MERCURY_ARMOR_HELMET = REGISTRY.registerItem("mercury_armor_helmet", MercuryArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MERCURY_ARMOR_CHESTPLATE = REGISTRY.registerItem("mercury_armor_chestplate", MercuryArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MERCURY_ARMOR_LEGGINGS = REGISTRY.registerItem("mercury_armor_leggings", MercuryArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MERCURY_ARMOR_BOOTS = REGISTRY.registerItem("mercury_armor_boots", MercuryArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> LUCK_COIN = REGISTRY.registerItem("luck_coin", LuckCoinItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAW_ENERGIUM = REGISTRY.registerItem("raw_energium", RawEnergiumItem::new, new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_ORE = block(PowerModBlocks.ENERGIUM_ORE);
	public static final DeferredItem<Item> ENERGIUM_DUST = REGISTRY.registerItem("energium_dust", EnergiumDustItem::new, new Item.Properties());
	public static final DeferredItem<Item> RAW_ENERGIUM_BLOCK = block(PowerModBlocks.RAW_ENERGIUM_BLOCK);
	public static final DeferredItem<Item> MERCURY_BATTERY = REGISTRY.registerItem("mercury_battery", MercuryBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MERCURY_BATTLE_AXE = REGISTRY.registerItem("mercury_battle_axe", MercuryBattleAxeItem::new, new Item.Properties());
	public static final DeferredItem<Item> DEEPSLATE_DEPLETED_ENERGIUM_ORE = block(PowerModBlocks.DEEPSLATE_DEPLETED_ENERGIUM_ORE);
	public static final DeferredItem<Item> DEEPSLATE_ENERGIUM_ORE = block(PowerModBlocks.DEEPSLATE_ENERGIUM_ORE);
	public static final DeferredItem<Item> DEEPSLATE_AMPLIFIER_ORE = block(PowerModBlocks.DEEPSLATE_AMPLIFIER_ORE);
	public static final DeferredItem<Item> DEEPSLATE_COPYRIUM_ORE = block(PowerModBlocks.DEEPSLATE_COPYRIUM_ORE);
	public static final DeferredItem<Item> MERCURY_BALL = REGISTRY.registerItem("mercury_ball", MercuryBallItem::new, new Item.Properties());
	public static final DeferredItem<Item> CHISELED_CURSED_STONE = block(PowerModBlocks.CHISELED_CURSED_STONE);
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS);
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS_SLAB = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS_SLAB);
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS_STAIRS = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS_STAIRS);
	public static final DeferredItem<Item> CURSED_STONE_CRACKED_BRICKS_WALL = block(PowerModBlocks.CURSED_STONE_CRACKED_BRICKS_WALL);
	public static final DeferredItem<Item> MUSIC_ARMOR_HELMET = REGISTRY.registerItem("music_armor_helmet", MusicArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_ARMOR_CHESTPLATE = REGISTRY.registerItem("music_armor_chestplate", MusicArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_ARMOR_LEGGINGS = REGISTRY.registerItem("music_armor_leggings", MusicArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_ARMOR_BOOTS = REGISTRY.registerItem("music_armor_boots", MusicArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_BATTERY = REGISTRY.registerItem("music_battery", MusicBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_GUITAR = REGISTRY.registerItem("music_guitar", MusicGuitarItem::new, new Item.Properties());
	public static final DeferredItem<Item> FREAKING_PARSNIP = REGISTRY.registerItem("freaking_parsnip", FreakingParsnipItem::new, new Item.Properties());
	public static final DeferredItem<Item> FREAKING_PARSNIP_BLOCK = block(PowerModBlocks.FREAKING_PARSNIP_BLOCK);
	public static final DeferredItem<Item> FREAKING_PARSNIP_SOUP = REGISTRY.registerItem("freaking_parsnip_soup", FreakingParsnipSoupItem::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_ARMOR_HELMET = REGISTRY.registerItem("plague_armor_helmet", PlagueArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_ARMOR_CHESTPLATE = REGISTRY.registerItem("plague_armor_chestplate", PlagueArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_ARMOR_LEGGINGS = REGISTRY.registerItem("plague_armor_leggings", PlagueArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_ARMOR_BOOTS = REGISTRY.registerItem("plague_armor_boots", PlagueArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_BATTERY = REGISTRY.registerItem("plague_battery", PlagueBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> PLAGUE_WALKING_STICK = REGISTRY.registerItem("plague_walking_stick", PlagueWalkingStickItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_HELMET = REGISTRY.registerItem("blue_flame_armor_helmet", BlueFlameArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_CHESTPLATE = REGISTRY.registerItem("blue_flame_armor_chestplate", BlueFlameArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_LEGGINGS = REGISTRY.registerItem("blue_flame_armor_leggings", BlueFlameArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_ARMOR_BOOTS = REGISTRY.registerItem("blue_flame_armor_boots", BlueFlameArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_BATTERY = REGISTRY.registerItem("blue_flame_battery", BlueFlameBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_MAGIC_FIREBALL = REGISTRY.registerItem("blue_magic_fireball", BlueMagicFireballItem::new, new Item.Properties());
	public static final DeferredItem<Item> BLUE_FLAME_SWORD = REGISTRY.registerItem("blue_flame_sword", BlueFlameSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_ARMOR_HELMET = REGISTRY.registerItem("gravity_armor_helmet", GravityArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_ARMOR_CHESTPLATE = REGISTRY.registerItem("gravity_armor_chestplate", GravityArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_ARMOR_LEGGINGS = REGISTRY.registerItem("gravity_armor_leggings", GravityArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_ARMOR_BOOTS = REGISTRY.registerItem("gravity_armor_boots", GravityArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_BATTERY = REGISTRY.registerItem("gravity_battery", GravityBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> GRAVITY_MACE = REGISTRY.registerItem("gravity_mace", GravityMaceItem::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_ARMOR_HELMET = REGISTRY.registerItem("smoke_armor_helmet", SmokeArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_ARMOR_CHESTPLATE = REGISTRY.registerItem("smoke_armor_chestplate", SmokeArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_ARMOR_LEGGINGS = REGISTRY.registerItem("smoke_armor_leggings", SmokeArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_ARMOR_BOOTS = REGISTRY.registerItem("smoke_armor_boots", SmokeArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_BATTERY = REGISTRY.registerItem("smoke_battery", SmokeBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> SMOKE_MUSKET = REGISTRY.registerItem("smoke_musket", SmokeMusketItem::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_ARMOR_HELMET = REGISTRY.registerItem("spirit_armor_helmet", SpiritArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_ARMOR_CHESTPLATE = REGISTRY.registerItem("spirit_armor_chestplate", SpiritArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_ARMOR_LEGGINGS = REGISTRY.registerItem("spirit_armor_leggings", SpiritArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_ARMOR_BOOTS = REGISTRY.registerItem("spirit_armor_boots", SpiritArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_BATTERY = REGISTRY.registerItem("spirit_battery", SpiritBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> SPIRIT_SICKLE = REGISTRY.registerItem("spirit_sickle", SpiritSickleItem::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_ARMOR_HELMET = REGISTRY.registerItem("form_armor_helmet", FormArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_ARMOR_CHESTPLATE = REGISTRY.registerItem("form_armor_chestplate", FormArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_ARMOR_LEGGINGS = REGISTRY.registerItem("form_armor_leggings", FormArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_ARMOR_BOOTS = REGISTRY.registerItem("form_armor_boots", FormArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_BATTERY = REGISTRY.registerItem("form_battery", FormBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> FORM_SAI = REGISTRY.registerItem("form_sai", FormSaiItem::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_ARMOR_HELMET = REGISTRY.registerItem("mind_armor_helmet", MindArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_ARMOR_CHESTPLATE = REGISTRY.registerItem("mind_armor_chestplate", MindArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_ARMOR_LEGGINGS = REGISTRY.registerItem("mind_armor_leggings", MindArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_ARMOR_BOOTS = REGISTRY.registerItem("mind_armor_boots", MindArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_BATTERY = REGISTRY.registerItem("mind_battery", MindBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> MIND_EPEE = REGISTRY.registerItem("mind_epee", MindEpeeItem::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_HELMET = REGISTRY.registerItem("golden_dust_armor_helmet", GoldenDustArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_CHESTPLATE = REGISTRY.registerItem("golden_dust_armor_chestplate", GoldenDustArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_LEGGINGS = REGISTRY.registerItem("golden_dust_armor_leggings", GoldenDustArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_ARMOR_BOOTS = REGISTRY.registerItem("golden_dust_armor_boots", GoldenDustArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_BATTERY = REGISTRY.registerItem("golden_dust_battery", GoldenDustBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> GOLDEN_DUST_STAFF = REGISTRY.registerItem("golden_dust_staff", GoldenDustStaffItem::new, new Item.Properties());
	public static final DeferredItem<Item> DARKNESS_ARMOR_HELMET = REGISTRY.registerItem("darkness_armor_helmet", DarknessArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> DARKNESS_ARMOR_CHESTPLATE = REGISTRY.registerItem("darkness_armor_chestplate", DarknessArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> DARKNESS_ARMOR_LEGGINGS = REGISTRY.registerItem("darkness_armor_leggings", DarknessArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> DARKNESS_ARMOR_BOOTS = REGISTRY.registerItem("darkness_armor_boots", DarknessArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> DARKNESS_BATTERY = REGISTRY.registerItem("darkness_battery", DarknessBatteryItem::new, new Item.Properties());
	public static final DeferredItem<Item> DARK_SWORD = REGISTRY.registerItem("dark_sword", DarkSwordItem::new, new Item.Properties());
	public static final DeferredItem<Item> THIRST_ARMOR_HELMET = REGISTRY.registerItem("thirst_armor_helmet", ThirstArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> THIRST_ARMOR_CHESTPLATE = REGISTRY.registerItem("thirst_armor_chestplate", ThirstArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> THIRST_ARMOR_LEGGINGS = REGISTRY.registerItem("thirst_armor_leggings", ThirstArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> THIRST_ARMOR_BOOTS = REGISTRY.registerItem("thirst_armor_boots", ThirstArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> CHAOS_ARMOR_HELMET = REGISTRY.registerItem("chaos_armor_helmet", ChaosArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> CHAOS_ARMOR_CHESTPLATE = REGISTRY.registerItem("chaos_armor_chestplate", ChaosArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> CHAOS_ARMOR_LEGGINGS = REGISTRY.registerItem("chaos_armor_leggings", ChaosArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> CHAOS_ARMOR_BOOTS = REGISTRY.registerItem("chaos_armor_boots", ChaosArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> HORROR_ARMOR_HELMET = REGISTRY.registerItem("horror_armor_helmet", HorrorArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> HORROR_ARMOR_CHESTPLATE = REGISTRY.registerItem("horror_armor_chestplate", HorrorArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> HORROR_ARMOR_LEGGINGS = REGISTRY.registerItem("horror_armor_leggings", HorrorArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> HORROR_ARMOR_BOOTS = REGISTRY.registerItem("horror_armor_boots", HorrorArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> FILTH_ARMOR_HELMET = REGISTRY.registerItem("filth_armor_helmet", FilthArmorItem.Helmet::new, new Item.Properties());
	public static final DeferredItem<Item> FILTH_ARMOR_CHESTPLATE = REGISTRY.registerItem("filth_armor_chestplate", FilthArmorItem.Chestplate::new, new Item.Properties());
	public static final DeferredItem<Item> FILTH_ARMOR_LEGGINGS = REGISTRY.registerItem("filth_armor_leggings", FilthArmorItem.Leggings::new, new Item.Properties());
	public static final DeferredItem<Item> FILTH_ARMOR_BOOTS = REGISTRY.registerItem("filth_armor_boots", FilthArmorItem.Boots::new, new Item.Properties());
	public static final DeferredItem<Item> EMPTY_CHARACTERISTICS_CARD = REGISTRY.registerItem("empty_characteristics_card", EmptyCharacteristicsCardItem::new, new Item.Properties());
	public static final DeferredItem<Item> CHARACTERISTICS_CARD = REGISTRY.registerItem("characteristics_card", CharacteristicsCardItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_DISC_CALL_OF_THE_PAST = REGISTRY.registerItem("music_disc_call_of_the_past", MusicDiscCallOfThePastItem::new, new Item.Properties());
	public static final DeferredItem<Item> MUSIC_DISC_ANCIENT_MOOD = REGISTRY.registerItem("music_disc_ancient_mood", MusicDiscAncientMoodItem::new, new Item.Properties());
	public static final DeferredItem<Item> CURSED_KNIGHT_SPAWN_EGG = REGISTRY.registerItem("cursed_knight_spawn_egg", properties -> new SpawnEggItem(PowerModEntities.CURSED_KNIGHT.get(), properties), new Item.Properties());
	public static final DeferredItem<Item> ENERGIUM_GOLEM_SPAWN_EGG = REGISTRY.registerItem("energium_golem_spawn_egg", properties -> new SpawnEggItem(PowerModEntities.ENERGIUM_GOLEM.get(), properties), new Item.Properties());
	public static final DeferredItem<Item> CURSED_SQUIRE_SPAWN_EGG = REGISTRY.registerItem("cursed_squire_spawn_egg", properties -> new SpawnEggItem(PowerModEntities.CURSED_SQUIRE.get(), properties), new Item.Properties());
	public static final DeferredItem<Item> CURSED_KEEPER_SPAWN_EGG = REGISTRY.registerItem("cursed_keeper_spawn_egg", properties -> new SpawnEggItem(PowerModEntities.CURSED_KEEPER.get(), properties), new Item.Properties());

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.registerItem(block.getId().getPath(), properties -> new BlockItem(block.get(), properties), new Item.Properties());
	}

	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void registerItemModelProperties(RegisterRangeSelectItemModelPropertyEvent event) {
			event.register(ResourceLocation.parse("power:fire_stone/recharge"), FireStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:air_stone/recharge"), AirStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:earth_stone/recharge"), EarthStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:water_stone/recharge"), WaterStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:ether_stone/recharge"), EtherStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:ice_stone/recharge"), IceStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:lightning_stone/recharge"), LightningStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:sound_stone/recharge"), SoundStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:crystal_stone/recharge"), CrystalStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:lava_stone/recharge"), LavaStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:rain_stone/recharge"), RainStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:tornado_stone/recharge"), TornadoStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:ocean_stone/recharge"), OceanStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:plants_stone/recharge"), PlantsStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:animals_stone/recharge"), AnimalsStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:metal_stone/recharge"), MetalStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:light_stone/recharge"), LightStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:shadow_stone/recharge"), ShadowStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:vacuum_stone/recharge"), VacuumStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:sun_stone/recharge"), SunStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:moon_stone/recharge"), MoonStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:space_stone/recharge"), SpaceStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:time_stone/recharge"), TimeStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:blood_stone/recharge"), BloodStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:technology_stone/recharge"), TechnologyStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:teleportation_stone/recharge"), TeleportationStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:explosion_stone/recharge"), ExplosionStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:amber_stone/recharge"), AmberStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:creation_stone/recharge"), CreationStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:destruction_stone/recharge"), DestructionStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:mist_stone/recharge"), MistStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:sand_stone/recharge"), SandStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:speed_stone/recharge"), SpeedStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:poison_stone/recharge"), PoisonStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:magnet_stone/recharge"), MagnetStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:mushrooms_stone/recharge"), MushroomsStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:mercury_stone/recharge"), MercuryStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:music_stone/recharge"), MusicStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:plague_stone/recharge"), PlagueStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:blue_flame_stone/recharge"), BlueFlameStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:gravity_stone/recharge"), GravityStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:smoke_stone/recharge"), SmokeStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:form_stone/recharge"), FormStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:mind_stone/recharge"), MindStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:golden_dust_stone/recharge"), GoldenDustStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:darkness_stone/recharge"), DarknessStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:energy_stone/recharge"), EnergyStoneItem.RechargeProperty.MAP_CODEC);
			event.register(ResourceLocation.parse("power:spirit_stone/recharge"), SpiritStoneItem.RechargeProperty.MAP_CODEC);
		}
	}
}
