### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.875 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.875 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.87,0.78],scale:1} ~0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.92,0.70,0.53],scale:1} ~0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.75 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.87,0.78],scale:1} ~0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.08,0.08,0.08],scale:1} ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.08,0.08,0.08],scale:1} ~0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.58,0.38],scale:1} ~0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.92,0.70,0.53],scale:1} ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.13,0.13,0.13],scale:1} ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.13,0.13,0.13],scale:1} ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.58,0.38],scale:1} ~0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.87,0.78],scale:1} ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.08,0.08,0.08],scale:1} ~0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.08,0.08,0.08],scale:1} ~0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.80,0.44,0.23],scale:1} ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.58,0.38],scale:1} ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.13,0.06],scale:1} ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.58,0.38],scale:1} ~0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.92,0.70,0.53],scale:1} ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.13,0.06],scale:1} ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.80,0.44,0.23],scale:1} ~0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.58,0.38],scale:1} ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.13,0.06],scale:1} ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~0 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.92,0.70,0.53],scale:1} ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.13,0.06],scale:1} ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.13,0.06],scale:1} ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.54,0.01,0.07],scale:1} ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~-0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.58,0.38],scale:1} ~-0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.13,0.06],scale:1} ~-0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.54,0.01,0.07],scale:1} ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~-0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.80,0.44,0.23],scale:1} ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.68,0.04,0.04],scale:1} ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.54,0.01,0.07],scale:1} ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.54,0.01,0.07],scale:1} ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.80,0.44,0.23],scale:1} ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.54,0.01,0.07],scale:1} ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.54,0.01,0.07],scale:1} ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~-0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.65,0.29,0.13],scale:1} ~-0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.61,0.21,0.07],scale:1} ~-0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.39,0.14,0.05],scale:1} ~-0.75 ~0 ~0.125 0 0 0 0 1 force @a
